### ISSUE TITLE
Spike: Configure Abbyy

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#165]

**Comment by jeremyf** [comment]
On [2022-11-30 I asked in Slack](https://assaydepot.slack.com/archives/C0313NJV9PE/p1669832988383359) about getting access to the Abbey SDK/API/Docs.

**Comment by jillpe** [comment]
Closed - client confirmed 2023-01-31 we will be moving forward with Tesseract Best instead of ABBYY
