### ISSUE TITLE
Mappings - NEW! Peer Review Yes/No

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#185]
# Accepted Criteria

- [x] Add Peer Reviewed content to OAI parser mapping
- [x] Add Peer Reviewed property to models; there are no peer-reviewed properties in RDF Vocal; we'll need to create our own.
- [x] Add Peer Reviewed to Show Pages
  - [x] if peer reviewed, it should say "Peer Reviewed" on the show page's metadata section
  - [x] if not, it should not display anything the show page's metadata section
- [x] Add Peer Reviewed to Edit Forms
  - [x] has a drop down for peer reviewed
    - [x] when nothing is selected, "Peer Reviewed" will save as nil (not display on show page)
    - [x] when it is selected, it will save as "Peer Reviewed" and display on the show 
- [x] Add Peer Reviewed as search facet
  - [x] There should be a Peer Review in the facet list, of the catalog search page

> We added peer review information to the OAI\_ADL metadata, and we'd like to see that appear in the next major upload. Can we add a mapping to the parser?  [Example](https://www.google.com/url?q=http://oai.adventistdigitallibrary.org/OAI-script?verb%3DGetRecord%26metadataPrefix%3Doai_adl%26identifier%3D13172991&sa=D&source=editors&ust=1671480230558736&usg=AOvVaw1cmmo2Ux8LC-mdDrQzv2sW) peer\_reviewed field reads “Peer Reviewed” and for articles that are NOT peer reviewed this field is skipped ([example](https://www.google.com/url?q=http://oai.adventistdigitallibrary.org/OAI-script?verb%3DGetRecord%26metadataPrefix%3Doai_adl%26identifier%3D13133044&sa=D&source=editors&ust=1671480230559001&usg=AOvVaw1BaF6l7P7fUKVGq61wHh7L)).
> 
> We'd like to see the Peer Review field on Hyku be filled or left blank in response to this metadata, and we'd like users to be able to filter by a Peer Review facet. Can we add this as a ticket? We will hold off a major reload of the repository until the Peer Review information can come in, so if we need to wait for the next sprint then this would be a high priority at that time.

From https://docs.google.com/document/d/1mIOT23UAilSO77pAlXYSWJEHw3YK3BNNQVTKNzd41ao/edit#

# Testing Instructions
1. Create an OAI import, offset: 80, limit 1 (this should result in a peer reviewed article)
2. visit the created work, see that peer reviewed is on the show page. Click edit, peer reviewed should be in the peer reviewed? drop down
3. Clear the selection from the edit page's drop down. save. peer reviewed? should no longer show in the show page's metadata. 

# Screenshots

<details>
<summary>Facet</summary>

<img width="399" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/46c70a72-ddda-4392-9679-860c5d0e4977">

</details>

<details>
<summary>Show page</summary>

<img width="712" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/5c9b2c80-2af3-4d06-bd0c-ccb73c219970">

</details>

<details>
<summary>Edit form</summary>

<img width="1014" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/823e43ee-32bc-4f1d-8b02-00155052d9c8">

</details>

**Comment by jeremyf** [comment]
I have done one aspect of the work, as indicated in the check box.  However this requires further review.

@kirkkwang should we pair on this today?

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- importer: https://sdapi.s2.adventistdigitallibrary.org/importers/42?locale=en
- work show page: https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/13129069_1_corinthians_11_and_14_how_does_a_woman_prophesy_and_keep_silence?locale=en

<details><summary>Peer Reviewed shows on the work show page and edit form upon initial import. After removing it, it no longer shows on the work show page.</summary>

![Journal Article 1 Corinthians 11 and 14 How does a woman prophesy and keep silence at th  ID 13129069_1_corinthians_11_and_14_how_does_a_woman_prophesy_and_keep_silence Hyku 2023-05-18 at 11 47 23 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/8588ce40-f45c-46f5-b040-6fbbf8ed78bf)

![1 Corinthians 11 and 14 How does a woman prophesy and keep silence at th  Journal Article  13129069_1_corinthians_11_and_14_how_does_a_woman_prophesy_and_keep_silence  Adventist Digital Library 2023-05-18 at 11 49 45 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/429aaf7b-69e8-4c4c-a700-039ae38bf8af)

![Journal Article 1 Corinthians 11 and 14 How does a woman prophesy and keep silence at th  ID 13129069_1_corinthians_11_and_14_how_does_a_woman_prophesy_and_keep_silence Hyku 2023-05-18 at 11 50 25 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/6f0bb4cf-e34e-4437-b284-9e81010c4702)

</details>

**Comment by KatharineV** [comment]
This is incredibly exciting. The peer review facet is indeed showing up on SDAPI staging. Thank you! This additional feature means **so much** and will make a huge difference with our stakeholders and users. 

- importer: https://sdapi.s2.adventistdigitallibrary.org/importers/44?locale=en
- work: https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/13129069_1_corinthians_11_and_14_how_does_a_woman_prophesy_and_keep_silence?locale=en
- importer: https://sdapi.s2.adventistdigitallibrary.org/importers/43?locale=en
- work: https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/13129077_1_2_kings_review?locale=en

**Comment by KatharineV** [comment]
This is working on SDAPI Production. [This article citation](https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13476193_contextualization_in_daniel_s_use_of_god_s_names_for_cross_cultura?locale=en) imported on 5/31, and it includes the Peer Review tag.
