### ISSUE TITLE
Mappings - Part of / collection names:

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#186]
# Summary

> Newly uploaded works do not contain part\_of periodical titles in the Hyku metadata display. Also, the works aren't deposited into their periodical title collections.
> 
> As of 2022-11-23, newly uploaded works did land in the correct collection and work-level metadata included the periodical.
> 
> Upload from 2022-11-23 with periodical title: [https://sdapi.b2.adventistdigitallibrary.org/concern/journal\_articles/13129042\_\_500\_000\_endowment?locale=en](https://www.google.com/url?q=https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13129042__500_000_endowment?locale%3Den&sa=D&source=editors&ust=1671480230559653&usg=AOvVaw0sXCkgzI3uEkgM36GhF423)
> 
> Upload from 2022-12-12 with no periodical title: [https://sdapi.b2.adventistdigitallibrary.org/concern/journal\_articles/13129468\_142\_baptized\_in\_chicago\_s\_west\_side?locale=en](https://www.google.com/url?q=https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13129468_142_baptized_in_chicago_s_west_side?locale%3Den&sa=D&source=editors&ust=1671480230560089&usg=AOvVaw1-X3TzG6g-ftv2u3LlSdNC)

From https://docs.google.com/document/d/1mIOT23UAilSO77pAlXYSWJEHw3YK3BNNQVTKNzd41ao/edit#

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by jeremyf** [comment]
Perhaps addressed by https://github.com/samvera-labs/bulkrax/issues/702

**Comment by ShanaLMoore** [comment]
To whoever picks up this ticket, base it off of https://github.com/scientist-softserv/adventist-dl/pull/266

**Comment by jeremyf** [comment]
Likely related to #203

**Comment by kirkkwang** [comment]
Ran import with code from `main` and it looks better.  Metadata shows `Periodical`.

#### Not working yet:
- [ ] deposit work into their periodical title collections

![image](https://user-images.githubusercontent.com/19597776/219258073-ab59e295-a9a1-4073-a187-c76951772b18.png)

**Comment by KatharineV** [comment]
Tested with an [import ](https://sdapi.s2.adventistdigitallibrary.org/importers/17?locale=en)on SDAPI staging. Confirmed that metadata shows the periodical, but the work is not deposited in the related collection (same behavior noted in SoftServ QA). 



![Image](https://user-images.githubusercontent.com/118196520/229806803-7e29c7f0-78c3-4511-9075-e881fab94008.png)

**Comment by KatharineV** [comment]
This is working as expected on SDAPI and ADL production.
