### ISSUE TITLE
OAI Import question for adl:periodical set:

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#197]
> I ran an import on adl:periodical with a limit of 100 works. No works imported, and the [importer](https://adl.b2.adventistdigitallibrary.org/importers/31?locale=en#collection-entries) just created a strangely-named and empty [collection](https://adl.b2.adventistdigitallibrary.org/collections/1f381fae-7764-4677-bff2-007e39a90efe?locale=en).  What caused this behavior? I'm also asking Eric what he knows about the periodical set. I hope he can tell me if there are works in that set that failed to import.

From https://docs.google.com/document/d/1mIOT23UAilSO77pAlXYSWJEHw3YK3BNNQVTKNzd41ao/edit#

## Testing Criteria

- [x] Create an OAI Importer with the following parameters:
  - Base URL :: http://oai.adventistdigitallibrary.org/OAI-script
  - Metadata Prefix :: `oai_adl`
  - Set :: `adl:periodical`
  - Limit :: 3
- [x] Run that importer
- [x] Open the importer and review the 3 collections.

Note the counts on the parser will be off.  [See this PR for reasons](https://github.com/scientist-softserv/adventist-dl/pull/217)

> I have taken efforts to properly address the parser's counts/totals but these
> things are quite challening given their upstream Bulkrax implementation. In
> other words expect the following counts to not show the correct summary
> totals.
>
> - Total Works
> - Total Collections
> - Total File Set
>
> Further, I have not addressed the collection's thumbnails. There is custom
> logic for uploading an image to a collection. I have written Issue #223 to
> track this functionality; PR #131 relates to this issue.
  
What does reviewing look look?  With the changes of this commit, you should be able to see the raw metadata and parsed metadata for each imported collection.  What we want to then see is that raw and parsed metadata on the imported collections.

<details>

<summary>What I Suspect will be the Raw Metadata</summary>

```
<metadata>
  <oai_adl>
    <aark_id>20000026</aark_id>
    <title>Pertandaan Zaman</title>
    <resource_type>Periodical</resource_type>
    <date_created>1901-01-01</date_created>
    <language>Malay</language>
    <extent>v. illus. 4to and fol.</extent>
    <source>Center for Adventist Research</source>
    <place_of_publication>Singapore</place_of_publication>
    <publisher>The Signs Press</publisher>
    <rights_statement>No Copyright - United States</rights_statement>
    <part_of>Rumah Tangga Dan Kesehatan</part_of>
    <related_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000026/20000026.OBJ.jpg</related_url>
    <thumbnail_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000026/20000026.TN.jpg</thumbnail_url>
    <work_type>Collection</work_type>
  </oai_adl>
</metadata>
```

```xml
<metadata>
  <oai_adl>
    <abstract>Signs of the Times presents articles that are considered to be helpful in assisting readers to live in modern society. The magazine focuses on lifestyle issues, health articles and Christian devotional and other religious articles. From its historical roots, the magazine emphasizes the second coming of Christ to this earth and living such lives so as to be able to meet Jesus at His second coming.</abstract>
    <aark_id>20000027</aark_id>
    <identifier>(OCoLC)2268533.; 0037-5047; 0040-6058; 64048061 //r84; sn 78000386</identifier>
    <title>Signs of the Times</title>
    <resource_type>Periodical</resource_type>
    <date_created>1874-01-01</date_created>
    <language>English</language>
    <description>Published in Oakland Jun 1874 to Aug 1904; Mountain View Sep 1904 to 1984.  Published by James White Jun 1874 to Sep 1874; Feb 1875 to 15 Apr 1875.  California Conference Oct 1874 to Jan 1875.
  Pacific SDA Publishing Association 22 Apr 1875 to 22 Mar 1880.  SDA Missionary Society 18 Mar 1880 to 7 Feb 1884.  International Tract and
  Missionary Society 14 Feb 1884 to Jun 1890.  Pacific Press Publishing Company Jul 1890 to Dec 1908.  Pacific Press Publishing Association Jan 1909 to 1984.</description>
    <extent>v. ill. 25-28.</extent>
    <source>Center for Adventist Research</source>
    <place_of_publication>Oakland, California, USA; Mountain View, California, USA</place_of_publication>
    <publisher>James White; California Conference of Seventh-day Adventists; Pacific SDA Publishing Association; The SDA Missionary Society; International Tract and Missionary Society; Pacific Press Publishing Company; Pacific Press Publishing Association</publisher>
    <rights_statement>No Copyright - United States</rights_statement>
    <subject>Bible Prophecies; Christian Life</subject>
    <related_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000027/20000027.OBJ.jpg</related_url>
    <thumbnail_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000027/20000027.TN.jpg</thumbnail_url>
    <work_type>Collection</work_type>
  </oai_adl>
</metadata>
```

```xml
<metadata>
  <oai_adl>
    <aark_id>20000028</aark_id>
    <identifier>0030-6894; sn 78005141</identifier>
    <title>Our Little Friend</title>
    <resource_type>Periodical</resource_type>
    <date_created>1890-01-01</date_created>
    <language>English</language>
    <extent>v.</extent>
    <source>Center for Adventist Research</source>
    <place_of_publication>Oakland, California, USA; Mountain View, California, USA; Boise, Idaho, USA</place_of_publication>
    <publisher>Pacific Press Publishing Association</publisher>
    <rights_statement>No Copyright - United States</rights_statement>
    <subject>Children -- Religious life; Periodicals</subject>
    <related_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000028/20000028.OBJ.jpg</related_url>
    <thumbnail_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000028/20000028.TN.jpg</thumbnail_url>
    <work_type>Collection</work_type>
  </oai_adl>
</metadata>
```

</details>

**Comment by KatharineV** [comment]
Eric checked on our end, and he told me that the adl:periodical set contains the "collections" that the adl:issue works fall into. For this reason, I'm placing ticket #197 high on the priority list because based on my reading of his answer, I need to run a complete adl:periodical import before running adl:issue. 

Here is the question I sent to Eric and the answer he gave me, for you to check my reasoning. 

KATHARINE: ADL Bulkrax Import question: We ran an import on adl:periodical with a limit of 100 works. No works imported, and the [importer ](https://adl.b2.adventistdigitallibrary.org/importers/31?locale=en#collection-entries)just created a strangely-named and empty [collection](https://adl.b2.adventistdigitallibrary.org/collections/1f381fae-7764-4677-bff2-007e39a90efe?locale=en). I’ve asked SoftServ to look into the Hyku side of what happened here. But from our end, what do we expect from the adl:periodical set? What is and/or should be in that set? Is there a reason on our end why Bulkrax found no works? 

 

ERIC: As far as the auto collection creation thing, the idea was that Bulkrax would create a periodical master collection the first time it saw one and then load the correct records into it. However doing the “is this a unique periodical” query each time a record hits the system was way too time consuming. So Rob turned off that check at one point. After the load was completed, he went back and wrote a script that automatically cleaned things up, grouping records by the name of their parent collections. Since under the hood each of what appears to be a duplicate collection has its own unique hyku id, Rob was able to automatically decide which collection would be the “keeper” and then move all the issues out of the “duplicate” collections into the one his code selected as the “keeper”. He then deleted all of the empty collections that were left. The reason you are not seeing one collection for each periodical issue is that the “duplicates” are created at the import batch level and not the item import level, if I recall correctly. As far as not importing works, I am seeing returns for both periodical related sets.

https://oai.adventistdigitallibrary.org/OAI-script?verb=ListIdentifiers&set=adl%3Aissue

https://oai.adventistdigitallibrary.org/OAI-script?verb=ListIdentifiers&set=adl%3Aperiodical

The idea was, not sure what SS wants now, to import the periodical set first and then import the issues. This was so that the periodical collection that holds the issues would get out metadata and not be one of those “auto created” collections.

**Comment by DeonFranklin** [comment]
This ticket passes Soft Serv QA.

**Comment by KatharineV** [comment]
I followed the testing instructions and created a new adl:periodical set importer on staging with a limit of 3 collections. The importer is done, but I don't see links to collections that I can test. The importer page only links one collection, and it is not a real collection (i.e. it isn't pulling from our OAI feed and it doesn't reflect any of the collection info I expect to see; it appears to be created by the importer and it is named for the set spec). Importer is here: https://adl.s2.adventistdigitallibrary.org/importers/32?locale=en

**Comment by jeremyf** [comment]
@KatharineV when in the importer page, click on the "Collection Entries"

![Image](https://user-images.githubusercontent.com/2130/215596242-f5ce1900-32a5-4b03-8c04-ffd186921d07.png)

Then click on a collection:



![Image](https://user-images.githubusercontent.com/2130/215596368-83aa7cfd-68bd-4943-960c-3e821dc5bcad.png)

Finally, click on the "Collection Link: Collection"

**Comment by KatharineV** [comment]
All looks good on staging. I tested the collections in [this import](https://adl.s2.adventistdigitallibrary.org/importers/16?locale=en). One is stuck "pending," but @jeremyf knows about that collection. It got stuck before.

**Comment by KatharineV** [comment]
I ran [a test import ](https://adl.b2.adventistdigitallibrary.org/importers/42?locale=en#collection-entries)of 3 periodicals on production, and it completed. The raw metadata looks right with these exceptions:

1. Parent Collection (part_Of) for [Pertandaan Zaman](https://adl.b2.adventistdigitallibrary.org/collections/e080d9cb-e388-48e3-8569-497d7c08763c?locale=en) is still incorrectly showing The Southern Watchman, which doesn't match the part_Of raw metadata. 

2. Fields with multiple values are not splitting at the semi-colon, so multiple values are displaying as a single metadata field. Example: [Signs of the Times](https://adl.b2.adventistdigitallibrary.org/collections/af7e7144-c534-47d1-8e15-ab549b2fb8cc?locale=en) has multiple publishers and two subjects, but they failed to split. 

These issues have been noted in other tickets, so I'm just restating it here to clarify that this test of 3 periodicals appears to work in general while continuing to have the specific problems that are being worked on overall. Thanks!

**Comment by KatharineV** [comment]
Clarification and update on my comment above:

I ran a [test import](https://adl.s2.adventistdigitallibrary.org/importers/32?locale=en#collection-entries) of 3 periodicals on staging, and [Pertandaan Zaman](https://adl.s2.adventistdigitallibrary.org/collections/6b27e5d2-28e5-49b0-aed6-305b0af3c795?locale=en) shows the correct textual metadata in the Part of field, but it is physically a part of the wrong [Parent Collection](https://adl.s2.adventistdigitallibrary.org/collections/83f0ecfe-de7d-4ba3-9e9a-fbde626cf56b?locale=en).

**Comment by jeremyf** [comment]
@KatharineV I fixed the underlying issue regarding assigning a collection to another collection.  One challenge is that my read of the logic is that each import will *add* to the existing relationship (e.g. the collection listing).

What I did was manually remove the relationships and then re-ran the importer.  I believe the metadata for [Pertandaan Zamaan](https://adl.s2.adventistdigitallibrary.org/collections/6b27e5d2-28e5-49b0-aed6-305b0af3c795?locale=en) shows the correct part of as well as collection relationship.

**Comment by KatharineV** [comment]
I created a periodical [import ](https://adl.s2.adventistdigitallibrary.org/importers/63?locale=en#work-entries)to run through the testing instructions for this ticket, and it is stuck pending. No entries are showing up. The import was set to bring in the first 3 periodicals again, to confirm that they land in their proper collection relationships. If the importer doesn't move out of pending, I will not be able to test this ticket. I'll update here if things change, but for now I'm assuming something is wrong and I won't get to finish testing...

**Comment by KatharineV** [comment]
Tried to test this ticket today (2/28/23) and the [importer ](https://adl.s2.adventistdigitallibrary.org/importers/65?locale=en#collection-entries)is stuck pending.

**Comment by jeremyf** [comment]
I went ahead and edited the importer via the UI.  I clicked "Update and Re-Harvest All Items"; that appeared to unstick the importer.

**Comment by KatharineV** [comment]
Periodicals are importing to Staging as expected. A[ test import today ](https://adl.s2.adventistdigitallibrary.org/importers/71?locale=en)(2023-03-13) completed without any problems.
