### ISSUE TITLE
Display: Links to AWS are showing in the Related URL field after a Bulkrax import.

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#201]
> [https://adl.b2.adventistdigitallibrary.org/concern/published\_works/20121647\_testimony\_for\_the\_church\_number\_17?locale=en](https://adl.b2.adventistdigitallibrary.org/concern/published_works/20121647_testimony_for_the_church_number_17?locale%3Den&sa=D&source=editors&ust=1671480230567072&usg=AOvVaw1xB8GjqXPGrZP_UW25IKXU)

From https://docs.google.com/document/d/1mIOT23UAilSO77pAlXYSWJEHw3YK3BNNQVTKNzd41ao/edit#

## Testing Criteria

With these testing instructions, you can also verify #197 (that is the create and run need not be repeated and while reviewing the 3 collections you can verify #197)

- [x] Create an OAI Importer with the following parameters:
  - Base URL :: http://oai.adventistdigitallibrary.org/OAI-script
  - Metadata Prefix :: `oai_adl`
  - Set :: `adl:periodical`
  - Limit :: 3
- [x] Run that importer
- [x] Open the importer and review the 3 collections.

**Comment by jeremyf** [comment]
@KatharineV how was the https://adl.b2.adventistdigitallibrary.org/concern/published_works/20121647_testimony_for_the_church_number_17?locale%3Den&sa=D&source=editors&ust=1671480230567072&usg=AOvVaw1xB8GjqXPGrZP_UW25IKXU ingested?  Is this an OAI ingest or via CSV?

**Comment by jeremyf** [comment]
Looking at the metadata, I see that it's imported from the OAI feed (using identifier 20121647).

The raw XML metadata is as follows:

```
<metadata>
  <oai_adl>
    <abstract>This tract is part of a series of testimonies written by Ellen White and published by the Seventh-day Adventist Church from 1855 to 1909.</abstract>
    <aark_id>20121647</aark_id>
    <identifier>b10134815_16; W11 .T5</identifier>
    <creator>White, Ellen Gould Harmon, 1827-1915</creator>
    <title>Testimony for the Church: Number 17</title>
    <resource_type>Book</resource_type>
    <date_created>1869-01-01</date_created>
    <language>English</language>
    <extent>no. in v. ; 15 cm.</extent>
    <source>Center for Adventist Research</source>
    <geocode>42.323991, -85.190425</geocode>
    <place_of_publication>Battle Creek, Michigan, USA</place_of_publication>
    <publisher>Steam Press of the Seventh-Day Adventist Publishing Association</publisher>
    <rights_statement>No Copyright – United States</rights_statement>
    <subject>History; Jesus Christ -- Love -- Health Reform -- Parenting; Visions -- Censures; Western Health Reform Institute (Battle Creek, Mich.); White, Ellen Gould Harmon, 1827-1915</subject>
    <related_url>https://adl-ebstore-repo.s3.amazonaws.com/20/1216/20121647/20121647.ARCHIVAL.pdf;https://adl-ebstore-repo.s3.amazonaws.com/20/1216/20121647/20121647.RAW.txt</related_url>
    <thumbnail_url>https://adl-ebstore-repo.s3.amazonaws.com/20/1216/20121647/20121647.TN.jpg</thumbnail_url>
    <work_type>PublishedWork</work_type>
  </oai_adl>
</metadata>
```

**Comment by DeonFranklin** [comment]
This ticket passes Soft Serv QA.

**Comment by KatharineV** [comment]
The links are not showing on new imports to Staging. Looks good.

**Comment by KatharineV** [comment]
Uploaded the adl:other set to staging via Bulkrax today, and there are no links to AWS showing in the Related URL field. [Example](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/20121895_letters_between_w_c_white_and_elder_j_w_boynton?locale=en).
