### ISSUE TITLE
Missing Hyku email invite

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#220]
# Summary
Yesterday I tried to create a new user on the ADL site, and the recipient didn't receive a registration email. I invited him using his work email, then I resent the invite to that email, then we tried an alternate gmail address. He never received a Hyku invite

# Accepted Criteria
- [x]  Answer question definitively: Are emails sending
- [x] Are emails getting blocked?
- [ ] If emails are getting blocked send information to Adventist and create a new ticket

# Notes

**Comment by jillpe** [comment]
I tested the contact button on Adventist's main production and it errored, which means email is just not working.

![Image](https://user-images.githubusercontent.com/84697174/210879221-5f3adcaf-c828-490f-8822-96f72935a701.png)

**Comment by jeremyf** [comment]
@KatharineV I did some digging and what I ultimately settled on was deleting the users.  Which means you'll need to recreate them.  It's a bit of a hammer, but tracking down emails is a difficult and time consuming challenge.

What I'd like to see is if you create the account, send the invite, if he will now receive it.  If not, I'll do more digging.  (I'm uncertain how Hyku exposes a resend invitation option, but I assume it's a configuration option of the library it uses.)

**Comment by KatharineV** [comment]
This is working in our latest tests.
