### ISSUE TITLE
Collection nesting appears broken - OAI Parser

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#233]
# Summary

When a collection is "part of" a larger parent collection, that metadata populates incorrectly. The <part_of> field in the OAI_ADL profile is not the parent collection, but it should be. 

See Slack thread: https://assaydepot.slack.com/archives/C0313NJV9PE/p1674495848906929?thread_ts=1674485123.289389&cid=C0313NJV9PE

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by ShanaLMoore** [comment]
To whoever picks up this ticket, base it off of https://github.com/scientist-softserv/adventist-dl/pull/266

**Comment by jeremyf** [comment]
This appears to be a duplicate of #203
