### ISSUE TITLE
Test Tesseract's "best" with provided samples

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#237]
In reading the tesseract documentation, there is "fast" and there is "best" options.  By default, "fast" is enabled.  However, the "fast" results are not adequate for a sizable subset of the existing material.  We need to see what the results of the "best" run against the set of files provided by Katharine.

This is a pre-cursor for determining our pathway for implementing OCR in the project.

We want to have the time and resulting text for each file both on fast and best mode.

**Comment by jillpe** [comment]
Samples to test can be found [here](https://drive.google.com/drive/u/0/folders/1PH6NFos44rEvg5-eF1lc4g_ogblNzbTi)

**Comment by kirkkwang** [comment]
Resulting files have been uploaded to the sample files [directory](https://drive.google.com/drive/u/0/folders/1PH6NFos44rEvg5-eF1lc4g_ogblNzbTi)

## Approach

We ran four different OCR processes which are:
- **fast** (default)
- **best** (using the english tessdata)
  - https://github.com/tesseract-ocr/tessdata_best/blob/main/eng.traineddata
- **fast** with basic preprocessing
- **best** with basic preprocessing
NOTE: We did notice that some of the material are not in english and perhaps running those native languages could yield better results.

### Preprocessing
- turn image grayscale
- despeckle
- resize to at least 8000px long edge
- turn image to group4 bitonal with a 70% threshold (this might be a little too heavy handed and can be tweaked)
NOTE: These are just some basic preprocessing procedures that can be adjusted and fine tuned should we desire.

### Time elapsed
In each OCR text file, at the very end, you will find how long it took to run the OCR for each process.
#### Ex:
<img width="734" alt="image" src="https://user-images.githubusercontent.com/19597776/215611262-e32ffa6e-aa62-43e6-ab44-8320f9fffdf3.png">

**Comment by KatharineV** [comment]
Can someone help me access the final OCR test results? I'd like to look at them more closely. Thank you!

**Comment by KatharineV** [comment]
The Tesseract Best results look adequate for our needs. We'd like to run tests on two more important representative PDFs (I'll email them to @jillpe ) just so we can say we've done our due diligence, but we are on board to adopt Tesseract. Thank you! This is great. I look forward to talking about this decision and what it means for the development timeline. See you later today, team!

**Comment by jeremyf** [comment]
I'm going to close this ticket and we'll need to create another ticket for "Implement Tesseract Best in Adventist"
