### ISSUE TITLE
OAI feed is incorrect after first page

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/adventist-dl#271]
## Details

The `metadataPrefix` is not being retained due to a bug with the `resumptionToken`.  Only the first page of 25 entries are being correctly profiled as `oai_adl` while subsequent entries default back to `oai_dc`.

## Implementation options

1. Rewriting to use the `identifier` mechanism (e.g. grab all the identifiers) then query the individual records.
2. Debug the resumption token error or how to better do it.

## Test Intructions

- [ ] Create an OAI Importer with the following
  - **base_url ::** http://oai.adventistdigitallibrary.org/OAI-script 
  - **metadata_prefix ::** oai_adl 
  - **set ::** adl:periodical 
  - **visibility ::** open 
  - **rights_statement ::** http://rightsstatements.org/vocab/CNE/1.0/ 
  - **override_rights_statement ::** 0 
  - **update_files ::** true 
- [ ] Run the importer
- [ ] There should be no entries in the "Work Entries" column/tab
- [ ] There should be 30 entries that are "completed" in the "Collection Entries" column/tab

## Related Issues

- #186 
- #240

**Comment by jeremyf** [comment]
Below are three details:

- **Test Ruby Code for OAI pagination** :: The code that queries the OAI feed
- Last record of the first page of OAI feed
- First record of the second page of the OAI feed

When the OAI library requests the second page, it does not send forward the correct parameters (e.g. the `metadataPrefix=oai_adl`).  This appears to be a bug in the [OAI gem](https://github.com/code4lib/ruby-oai/).

<details>
<summary>Test Ruby Code for OAI pagination</summary>

```ruby
gem "oai"
require 'oai'
require 'debug'
client = OAI::Client.new(
  "http://oai.adventistdigitallibrary.org/OAI-script",
  headers: { from: "jeremy@scientist.com" },
  parser: 'libxml')

opts = {
  metadata_prefix: "oai_adl"
}

sets = ["adl:periodical"]
sets.each do |set|
  records = client.list_records(opts.merge(set: set))

  records.full.each_with_index do |r, i|
    next if i < 24
    break if i > 25
    puts "Index: #{i}"
    puts r._source.to_s
  end
end
```

</details>

<details>
<summary>Last record of the first page of OAI feed</summary>

```xml
<record>
      <header>
        <identifier>20000061</identifier>
        <datestamp>2022-12-15T05:09:20Z</datestamp>
        <setSpec>adl:periodical</setSpec>
      </header>
      <metadata><oai_adl><abstract>School paper for Washington University.</abstract><aark_id>20000061</aark_id><identifier>CAR Periodical</identifier><title>Columbia Journal: 1981-; The Sligonian: 1916-1980</title><resource_type>Periodical</resource_type><date_created>1916-01-01</date_created><language>English</language><description>Spring Annual issue served as the college yearbook, 1916-1925.</description><extent>65 v. : ill. ; 23-56 cm.</extent><source>Center for Adventist Research</source><place_of_publication>Takoma Park, Maryland, USA</place_of_publication><publisher>Student's Association of Washington Missionary College</publisher><rights_statement>No Copyright - United States</rights_statement><subject>Columbia Union College; Education; Washington Missionary College (Takoma Park, Md.); Washington University</subject><related_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000061/20000061.OBJ.jpg</related_url><thumbnail_url>https://adl-ebstore-repo.s3.amazonaws.com/20/0000/20000061/20000061.TN.jpg</thumbnail_url><work_type>Collection</work_type></oai_adl></metadata>
    </record>
```

</details>

<details>
<summary>The first record of the second page</summary>

```xml
<record>
      <header>
        <identifier>20000062</identifier>
        <datestamp>2022-12-15T05:09:20Z</datestamp>
        <setSpec>adl:periodical</setSpec>
      </header>
      <metadata><oai_dc:dc xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:srw_dc="info:srw/schema/1/dc-schema" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
  <dc:description>Official publication of the Atlantic Union Conference of Seventh-day Adventists</dc:description>
  <dc:rights>No Copyright - United States</dc:rights>
  <dc:subject>BX6137.A8 A1</dc:subject>
  <dc:type>periodical</dc:type>
  <dc:identifier>20000062</dc:identifier>
  <dc:language>English</dc:language>
  <dc:contributor/>
  <dc:date>1902-01-01-1902-12-31</dc:date>
  <dc:publisher>Atlantic Union Conference of Seventh-day Adventists</dc:publisher>
  <dc:format>v. : ill. 28 cm.</dc:format>
  <dc:format>print</dc:format>
  <dc:relation/>
  <dc:subject>Atlantic Union Conference of Seventh-day Adventists</dc:subject>
  <dc:subject>Seventh-day Adventists</dc:subject>
  <dc:title>Atlantic Union Gleaner</dc:title>
  <dc:title/>
  <dc:type>Text</dc:type>
</oai_dc:dc></metadata>
    </record>
```

</details>

**Comment by jeremyf** [comment]
In the `oai_adl` prefix there is for the `adl:periodical` set, I wrote the following ruby code.  There are 153 records in the set.  What I found is that when it hits the 153 record it never completes/exits the loop.  The end result is I see it hang with the last line of logged output say `Index: 152`.  The program never completes.

<details>
<summary>Ruby Code to Loop through full records</summary>

```
gem "oai"
require 'oai'
require 'debug'
client = OAI::Client.new(
  "http://oai.adventistdigitallibrary.org/OAI-script",
  headers: { from: "jeremy@scientist.com" },
  parser: 'libxml')

opts = {
  metadata_prefix: "oai_adl"
}

sets = ["adl:periodical"]
sets.each do |set|
  records = client.list_records(opts.merge(set: set))

  records.full.each_with_index do |r, i|
    puts "Index: #{i}"
  end
end
```

</details>

**Comment by jeremyf** [comment]
Digging deeper, it appears that the OAI implementation of Adventist is not per the OAI spec.  If I make changes to passing the original metadata prefix, then there's an exception about violating the OAI format.
