### ISSUE TITLE
Make the part and part_of properties facetable

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#280]
In our <2023-02-28 Tue> conversation, we want to make the part and part_of properties facetable.  These fields represent the collections that they are part of.  By introducing the facet on these fields, we can deliver on the feature of searching within a collection, without needing to worry about the challenges we've experienced in auto-creating collections.

This builds on the recommendation here: https://docs.google.com/document/d/1Cckk2kDbZ9V9f-D--DW0hIF5R3ykeRH4XFgJ6RyPsYU/edit#heading=h.j2x8gqss93ii

Related to #281

**Comment by ShanaLMoore** [comment]
in the show page, part and part of would be a link to the facet. 

in the catalog it'll be a facet on the left.

**Comment by jeremyf** [comment]
When I go to the catalog page, I see the part of section.  The facet for the show page, however, requires more work; which for now we will set as lower priority (investigating the steps to fix this, I saw that it would require quite a bit more work)

![Image](https://user-images.githubusercontent.com/2130/224724987-c56e52ea-e3a7-415f-a8da-f4a945ee78b5.png)
