### ISSUE TITLE
Remove automatic collection creation from Adventist Entry

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#281]
In our <2023-02-28 Tue> meeting, we agreed to stopping the auto-matic collection creation by way of the part and part_of properties.  This was creating all kinds of heartburn and head-aches.  We still need to have collection creation for non-part/part\_of properties.

See the following document for details: https://docs.google.com/document/d/1Cckk2kDbZ9V9f-D--DW0hIF5R3ykeRH4XFgJ6RyPsYU/edit#heading=h.j2x8gqss93ii

## Testing Instructions

Ideally, you are starting from a relatively "clean" repository of data; because any existing works associated with collections will not be disassociated those collections.

- [x] Create and run a Bulkrax OAI importer with the following parameters
  - `base_url`: http://oai.adventistdigitallibrary.org/OAI-script 
  - `metadata_prefix`: oai_adl 
  - `set`: adl:periodical
  - `visibility`: open 
  - `limit`: 5
- [x] The parsed metadata for the import entry with AARK_ID of `20000026` should:
  - [x] Have a `part_of` equal to `["Rumah Tangga Dan Kesehatan"]`.
  - [x] **Not** have a `parents`.
- [x] Review the import entry's Hyku collection record, 
  - [x] It should have a "Part of Rumah Tangga Dan Kesehatan" detail.
  - [x] It should not have a link to the aforementioned collection (see note 1)
  
The `part_of` is the title of a collection.  But it is the `parents` value that creates the connection to the collection.  Depending on when this is reviewed, we may introduce a Facet link for the `part_of` value (that is link to the catalog with a prepopulated search term).

*Note 1:* Given that we've been importing from OAI regularly, it is possible that the 20000026 record will already be associated with a collection.  In that case the checkbox for note 1 cannot be verified; but the other line items can be verified.

Related to #280

**Comment by jillpe** [comment]
SoftServ QA: PASS

[URL test](https://adl.s2.adventistdigitallibrary.org/importers/69?locale=en#collection-entries)

* Created and ran Bulkrax OAI Importer with the above parameters
* Found import entry with AARK_ID of 20000026 under collections entry tab and opened it
* Viewed the Parsed Metadata and found `part_of` = `["Rumah Tangga Dan Kesehatan"]`
* It does NOT have parents
* Found "Part of Rumah Tangga Dan Kesehatan" in the Hyku Collection record and opened
* Saw import entry 20000026 linked in the collection

<details>
<summary>Screenshots below</summary>


![Image](https://user-images.githubusercontent.com/84697174/223858879-dabb1e59-0f10-43d2-b71d-67ceed353eda.png)



![Image](https://user-images.githubusercontent.com/84697174/223858888-2763f208-89b6-4f01-ad6e-1709a179f82f.png)



![Image](https://user-images.githubusercontent.com/84697174/223858895-714d8ae5-d0a6-4431-b9e8-fed5a0b3cc6e.png)



![Image](https://user-images.githubusercontent.com/84697174/223858902-d682b137-e813-4d07-a7f0-ce464138b299.png)


</details>

**Comment by KatharineV** [comment]
I followed the testing instructions on ADL and SDAPI staging. As Jeremy suggested, previous OAI imports meant that the parent collection link persisted for collection 20000026. So, I ran a larger import on SDAPI staging where fewer periodicals have been brought in. My importer is [here](https://sdapi.s2.adventistdigitallibrary.org/importers/14?locale=en), and collection [20000075 ](https://sdapi.s2.adventistdigitallibrary.org/collections/d105178b-b243-47e2-8b27-da5963128878?locale=en)provides evidence that the parent collection link is no longer populating. 

In the screenshot below, note that "Part of" reads "Jubilee Standard," but there is no parent collection link. 

![Image](https://user-images.githubusercontent.com/118196520/224087505-abb7fffd-6dfa-492d-a570-f574a14e955a.png)

**Comment by KatharineV** [comment]
I tested this ticket on [production](https://adl.b2.adventistdigitallibrary.org/collections/e080d9cb-e388-48e3-8569-497d7c08763c?locale=en), and I can confirm that collection 20000026 has the correct "part of" metadata. The (incorrect) parent collection was already populated from a previous import.
