### ISSUE TITLE
The child work (that is a single page from the PDF) should be suppressed from the search query.

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#286]
# Summary

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

Testing: ON STAGING

    Create a work with an attached PDF file.
    The work should split into child works with attached jps (one per page), which are all attached to the parent work.
    Search for a piece of text contained in the PDF file.

Expected Result: Only the parent work shows in the result list

# Notes

**Comment by jillpe** [comment]
part of #278

**Comment by laritakr** [comment]
Testing:

1. Create a work with an attached PDF file. 
2. The work should split into child works with attached PNGs (one per page), which are all attached to the parent work.
3. Search for a piece of text contained in the PDF file. 

Expected Result: Only the parent work shows in the result list

**Comment by laritakr** [comment]
There is a delayed job that runs to associate the parent work and child works. This gets scheduled for a 10 minute delay, to allow all of the child works to have time to complete before we try to connect them. You would have to check the sidekiq ui to see the job if there is still a scheduled job pending completion.

When I checked, it looked like the associations have been made, but there are no thumbnails on the child works, so derivatives are most likely still running. 

If you check again after everything completes, I anticipate this will finish and work correctly. Please report back with what you see.

**Comment by KatharineV** [comment]
Thanks for the insight into the delayed job. I checked the example above, and the child works are now suppressed in the catalog search. Yay!

Successful catalog search for a phrase that appears in the PDF, "maritime plain at Joppa." 


![Image](https://user-images.githubusercontent.com/118196520/225048568-fb9dc6b7-11f9-4826-a1b2-e56500029ff0.png)


Within the viewer, the child works show as expected. The thumbnail also shows, and it is presented first, which is not desired behavior. If possible, I'd like to suppress the thumbnail from the viewer. That's an issue for a different ticket, though. For #286, it looks like child works are behaving as expected on adl.s2.

**Comment by laritakr** [comment]
> This example is weird because the parent PDF was accidentally uploaded twice. I then deleted the second instance of the parent PDF, so it isn't there anymore. But there are duplicate child works, as a result. Could this be why some child works are showing in the catalog? 

I would expect that when the parent work was deleted, the child works were reindexed to no longer have the "is_child" value indexed, which would mean it once again shows in the search results. 

> Even if it is, there will be instances where we have multiple PDFs attached to a work. Our adl:issue set in the OAI feed contains many records with both an archival and a reader PDF. In those cases, we would only want to feature one of the two PDFs in the viewer, so we don't have duplicates. Any advice for us?

This is a much more complex issue. Currently every PDF on a work will be split into child works, and if you attach more than one PDF, they would be split as well (It would say `Pdf 2, Page x`) though multiple PDFs are not fully supported if they are not uploaded all at one time. We would need to brainstorm options to solve this. 

A few thoughts I have offhand: we could possibly override this behavior and only split the first PDF that gets attached but then there is the question of which one to split. Another better option might be to attach the archival PDF as a child work of a different work type which is not set to split works. In this case the archival pdf's work would be a child work so it would not show in search results.

**Comment by KatharineV** [comment]
Thanks! Your comment is extremely helpful. Thinking about how the iiif_print gem works has uncovered a flaw in our plan for Hyku. Namely, we have multiple PDFs attached to many of the works in our old repository that have imported / will be imported into Hyku. There was reasoning for this that made sense at the time. However, the features the iif_print gem brings to the digital library are higher priority, so we are open to changing things--whatever it takes--so we don't have duplicate derivatives in the viewer.

**Comment by jillpe** [comment]
Spike: Retest this locally to try to reproduce error

**Comment by kirkkwang** [comment]
Tested locally and it worked as expected

**Comment by ShanaLMoore** [comment]
# QA RESULTS:

**Comment by KatharineV** [comment]
Tested with a new upload to staging, and all works as expected. https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/0dccb769-cd80-4bb3-a09f-b8becbe9a8e1?locale=en

**Comment by KatharineV** [comment]
Working as expected on production.
