### ISSUE TITLE
Configure Image model type to only generate text derivatives (e.g. OCR and full text)

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#294]
# Summary

Add OCR configuration to the Image model only. 

## Acceptance Criteria

- [ ] Only an image work type should have OCR

## Testing Instructions 

Create an Image work type and attach a pdf or jpg to it. Whatever file you attach should have simple text. 

After import + sidekiq is finished, check that those file types had derivatives made by opening the actions dropdown (where the file set is listed in the items section). There should be txt and json listed options. 

Additionally, if you open the txt file it should display words. Those words should be searchable via the UV and catalog search. If using the sample file, you should be able to search for words like "eyes" and "minute".

Using the same file, create a non-Image work type. It should not generate txt derivatives. 

### Sample File

![Image](https://user-images.githubusercontent.com/10081604/224077798-18237316-0adb-43d6-abcc-0ded5570e427.jpg)

**Comment by jillpe** [comment]
SoftServ QA Findings

[Image Work ](https://adl.s2.adventistdigitallibrary.org/concern/images/b1afa5f2-468f-4070-bc7d-817ab753eee5?locale=en)
* Uploaded sample file (jpeg) as a an image work
* Derivatives created are xml, thumnail, txt, and json (see screenshots)
* txt file contained all the words (see screenshots)
* was able to search the words in the UV
<details>
<summary>Image Screenshots</summary>


![Image](https://user-images.githubusercontent.com/84697174/224119961-0edc99a0-f486-45b8-a3c2-44a9095f5de9.png)



![Image](https://user-images.githubusercontent.com/84697174/224119966-ab79c9ff-07d1-4644-96c7-e170071cda11.png)



![Image](https://user-images.githubusercontent.com/84697174/224119973-29684f16-9512-444e-84e7-b2744f31d949.png)


</details>

[Generic Work](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/2dde9e47-20d4-4c48-954e-22d2b58f284e?locale=en)
* Uploaded sample file (jpeg) as a generic work
* Created 2 items: (see screenshots)
    1) Derivatives: txt, jp2, json, pdf, xml, tiff, thumbnail
    2) Derivatives: jp2, pdf 
* was able to search the words in the UV

<details>
<summary>Generic work Screenshots</summary>


![Image](https://user-images.githubusercontent.com/84697174/224120203-ee7e2484-2afa-4795-9d92-0ceb1ef396c3.png)



![Image](https://user-images.githubusercontent.com/84697174/224120252-26a0bf2e-a3b9-4681-99cd-e93ca285a7d6.png)


</details>

[Conference Item](https://adl.s2.adventistdigitallibrary.org/concern/conference_items/94b9b21d-303c-4682-949f-7e951d734d80?locale=en)
* Used same sample file and uploaded as a conference item
* Derivatives created (see screenshot): txt, jp2, json, pdf, xml, tiff, thumbnail
* was able to search the words in the UV

<details>
<summary>Conference Item Screenshots</summary>


![Image](https://user-images.githubusercontent.com/84697174/224120356-8a7d6b26-8f25-4884-a474-7b3666d94374.png)


</details>

**Comment by laritakr** [comment]
Note that ticket #293 removes the TIFF derivatives, so once that is merged and deployed, the expected results will vary from Jill's results.

**Comment by jeremyf** [comment]
As of 2023-03-14, given that we're only going to generate text derivatives for all of Adventist, this is something we can close as there's a more general solution working it's way through the queue.
