### ISSUE TITLE
exclude thumbnail derivatives from displaying in the UV

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#318]
# Summary

TN.jpg files are being rendered in the UV.

Per Katharine, 

"Can we exclude thumbnails from showing in the UV? [As in this example](https://adl.s2.adventistdigitallibrary.org/concern/published_works/20214381_an_appeal_to_the_youth_funeral_address_of_henry_n_white?locale=en), it loads first and it creates a confusing user experience."

# Acceptance Criteria

- [ ] Thumbnails should not be included in the UV. 

# Screenshots or Video

link to example: https://adl.s2.adventistdigitallibrary.org/concern/published_works/20214381_an_appeal_to_the_youth_funeral_address_of_henry_n_white?locale=en

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/10081604/226644510-df14a43e-3d8c-43b0-9ad4-862799a3d8e6.png">

# Testing Instructions

Ask katharine or jeremy how to import a thumbnail file. 

[Update](https://assaydepot.slack.com/archives/G0311DN2YCA/p1680633808266459) per Jeremy: 

The thumbnail file is imported via the OAI importer.
You can create an OAI import with:
metadataPrefix: “oai_adl”
set: “adl:thesis”
URL: http://oai.adventistdigitallibrary.org/OAI-script
And limit the import to one or two (the first and second record has a thumbnail).

After that, visit the work's show page/UV and verify that the file ending with TN.jpg shows up in the items section, but not in the UV

# Notes

**Comment by ShanaLMoore** [comment]
Dev notes: We can either clean up the data or change the manifest to skip anything that has a filename of .TN. etc.

**Comment by DiemBTran** [comment]
blocked, staging adl tenant is busted

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- importer: https://sdapi.s2.adventistdigitallibrary.org/importers/25?locale=en
- work with thumbnail: https://sdapi.s2.adventistdigitallibrary.org/concern/theses/20121820_an_investigation_of_the_syntax_of_words_denoting_time_in_the_new_t?locale=en

<details><summary>The file ending with TN.jpg shows up in the items section, but not in the UV
</summary>

![Thesis An Investigation of the Syntax of Words Denoting Time in the New Testament ID 20121820_an_investigation_of_the_syntax_of_words_denoting_time_in_the_new_t Hyku 2023-04-05 at 11 24 59 AM](https://user-images.githubusercontent.com/29311858/230170852-d1c76081-6514-431b-a397-b85023e17d5f.jpg)
![Thesis An Investigation of the Syntax of Words Denoting Time in the New Testament ID 20121820_an_investigation_of_the_syntax_of_words_denoting_time_in_the_new_t Hyku 2023-04-05 at 11 24 49 AM](https://user-images.githubusercontent.com/29311858/230170871-25c17b23-5d4e-415c-91e1-6cad06aacce5.jpg)
</details>

**Comment by ShanaLMoore** [comment]
cc @KatharineV for client QA, you'll want to use the sdapi tenant after we reindex it. We plan on doing so tonight. Otherwise we can provide videos or screenshots if you'd like a faster review.

**Comment by KatharineV** [comment]
Tested on SDAPI [staging ](https://sdapi.s2.adventistdigitallibrary.org/concern/theses/20121820_an_investigation_of_the_syntax_of_words_denoting_time_in_the_new_t?locale=en)and found that thumbs are excluded from the UV. Hooray! Thank you.
