### ISSUE TITLE
import processing time for ADL

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#322]
# Summary

Client started this importer 8 days ago and it's still running. 

Is there any way we can improve the speed of this? 

# Acceptance Criteria

- [ ]

# Screenshots or Video

# Testing Instructions

# Notes

**Comment by kirkkwang** [comment]
Importer: https://adl.s2.adventistdigitallibrary.org/importers/72

**Comment by jillpe** [comment]
closed - will be covered with SpaceStone work
