### ISSUE TITLE
BUG: PROD UV doesn't render any images that belong to a collection

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#326]
# Summary

The UV is showing a black screen instead of delivering TIFF or JPEG 

link to slack thread/convos: 

1. https://assaydepot.slack.com/archives/C0313NJV9PE/p1679508856949789
2. https://assaydepot.slack.com/archives/G0313NK5NMA/p1679516476540619

# Acceptance Criteria

- [ ]

# Screenshots or Video

![Image](https://user-images.githubusercontent.com/10081604/227064658-ea1e45df-39c9-4030-8806-d0884b79b7e4.png)

# Testing Instructions

Create a generic work. Add an image to it: ![Image](https://user-images.githubusercontent.com/10081604/227064723-6c789716-dcc6-4a56-ad4c-1f6139836940.jpg)

Add that work to a collection. 

Revisit the work. It should still render the image in the UV. 

# Notes

While debugging with Kirk, we noticed several of the 500 errors had an 'undefined method #member_of_collection_ids' near it. We then noticed that some works on staging was behaving the same way as prod. They are both on the same sha. 

We opened a working UV work, and tried adding it to a collection. As soon as we did that, the UV wouldn't render.

This is reproducible locally.

**Comment by kirkkwang** [comment]
Link to busted image after adding a collection:
https://adl.s2.adventistdigitallibrary.org/concern/images/86e6afad-c3b6-4094-ab48-2d553af710e0?locale=en

```sh
D, [2023-03-22T23:10:27.514840 #1] DEBUG -- : [bccfa702a80d99a1ad8b4587df8fc4f3] Solr fetch (52.3ms)
I, [2023-03-22T23:10:27.577435 #1]  INFO -- : [bccfa702a80d99a1ad8b4587df8fc4f3] Completed 500 Internal Server Error in 121ms (ActiveRecord: 7.3ms)
D, [2023-03-22T23:10:27.580185 #1] DEBUG -- : [bccfa702a80d99a1ad8b4587df8fc4f3]   [1m[36mAccount Load (0.7ms)[0m  [1m[34mSELECT  "public"."accounts".* FROM "public"."accounts" WHERE "public"."accounts"."tenant" = $1 LIMIT $2[0m  [["tenant", "public"], ["LIMIT", 1]]
I, [2023-03-22T23:10:27.593814 #1]  INFO -- : [bccfa702a80d99a1ad8b4587df8fc4f3] Sending event 8aba5bc2abea4413a70b327e2bc3b44b to Sentry
F, [2023-03-22T23:10:27.648464 #1] FATAL -- : [bccfa702a80d99a1ad8b4587df8fc4f3]   
F, [2023-03-22T23:10:27.648674 #1] FATAL -- : [bccfa702a80d99a1ad8b4587df8fc4f3] NoMethodError (undefined method `member_of_collection_ids' for #<ActiveFedora::SolrHit:0x00007fb416406d80>):
```

**Comment by jillpe** [comment]
closed - verified in slack https://assaydepot.slack.com/archives/C0313NJV9PE/p1679583066130319?thread_ts=1679508856.949789&cid=C0313NJV9PE
