### ISSUE TITLE
Run Imports on local environment (QA/follow up)

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#337]
# Summary 
We want to test imports on a fresh environment to see if we get any errors

https://assaydepot.slack.com/archives/C0313NJV9PE/p1680103196811269

# Accepted Criteria
- [ ] imports Katharine sent over are run on local environment, documented, and shared with her
- [ ] follow up tickets are created on any errors we run in to
- [ ] Tickets marked 'Data Related' have been looked at and closed if no longer relevant

# Notes

- [x] #319 
- [ ] #321 
- [x] #341

**Comment by ShanaLMoore** [comment]
QA locally since we can't do it in staging right now. Please add photos and videos for each point.

**Comment by jillpe** [comment]
Imports:


[Staging 5 samples Metadata.xlsx](https://github.com/scientist-softserv/adventist-dl/files/11142665/Staging.5.samples.Metadata.xlsx)
[b15077391_001800010001.pdf](https://github.com/scientist-softserv/adventist-dl/files/11142669/b15077391_001800010001.pdf)
[b15077391_001500310002.pdf](https://github.com/scientist-softserv/adventist-dl/files/11142666/b15077391_001500310002.pdf)
[b15077391_001500310001.pdf](https://github.com/scientist-softserv/adventist-dl/files/11142668/b15077391_001500310001.pdf)
[b15077391_001500130001.pdf](https://github.com/scientist-softserv/adventist-dl/files/11142670/b15077391_001500130001.pdf)
[b15077391_001800010002.pdf](https://github.com/scientist-softserv/adventist-dl/files/11142667/b15077391_001800010002.pdf)

**Comment by laritakr** [comment]
I'm getting error `Error: CSV::MalformedCSVError - Invalid byte sequence in UTF-8 in line 1.` on the CSV. Anyone have ideas on what to try?

**Comment by jeremyf** [comment]
I imported the XLS file into Google Sheets and exported via CSV.

[Staging 5 samples Metadata.csv](https://github.com/scientist-softserv/adventist-dl/files/11149767/Staging.5.samples.Metadata.csv)

**Comment by laritakr** [comment]
Still getting the same error

**Comment by ShanaLMoore** [comment]
@kirkkwang We may be able to use the sdapi tenant: https://sdapi.s2.adventistdigitallibrary.org/

import locally but also kick off some on sdapi and see if that works (after we deploy the bulkrax fixes)

**Comment by laritakr** [comment]
File to use for importing is here: https://drive.google.com/file/d/1baFjh8xc0HpOGrR2ODtpQxvvR6m6kdE2/view?usp=share_link

**Comment by laritakr** [comment]
Second file for importing is here... better quality scans and creates `Published Works`: https://drive.google.com/file/d/188eqfKvA0ZXf2sOfNi7qia70KfUh1KhS/view?usp=share_link
