### ISSUE TITLE
Spike: Metadata mapping and search filtering

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#339]
# Summary

ref: https://assaydepot.slack.com/archives/C0313NJV9PE/p1680538944852799

EXAMPLE - https://adl.b2.adventistdigitallibrary.org/concern/published_works/22249997_an_original_essay_on_the_immateriality_and_immortality_of_the_huma?locale=en

![Image](https://user-images.githubusercontent.com/10081604/229570880-d4d3e21a-e653-4ec1-827c-3dac1abc02b8.png)

# Acceptance Criterie

# Testing Instructions 

# Notes 

mappings spreadsheet: https://docs.google.com/spreadsheets/d/1GEsyaFNias1JmnAkRLZbMYsBIaV-1rxl/edit#gid=1638457955

**Comment by jillpe** [comment]
lowest high priority

**Comment by jeremyf** [comment]
Working Notes:

-   **AARK ID:** 22249997
-   **OAI ADL Record:** <http://oai.adventistdigitallibrary.org/OAI-script?verb=getRecord&metadataPrefix=oai_adl&identifier=22249997>
-   **MODS Record:** <http://oai.adventistdigitallibrary.org/OAI-script?verb=getRecord&metadataPrefix=mods&identifier=22249997>

In the *OAI ADL Record* we have the `part_of` element containing “John N. Andrews Library Collection”.  In the *MODS Record* we have the `relatedItem/titleInfo/title` element containing “John N. Andrews Library Collection”.

Looking at the Bulkrax parser mapping:

-   **OAI Mapping:** `'part_of' => { from:  ['part_of'] }` and `'part' => { from:  ['part_of'] }` ([see code](https://github.com/scientist-softserv/adventist-dl/blob/7820c25827600a1beeb13944c83db45d320b1942/config/initializers/bulkrax.rb#L58-L59))
-   **CSV Mapping:** `'part_of' => { from:  ['relation.isPartOf'] }` and `'part' => { from:  ['relation.isPartOf'] }` ([see code](https://github.com/scientist-softserv/adventist-dl/blob/7820c25827600a1beeb13944c83db45d320b1942/config/initializers/bulkrax.rb#L90-L91))

The following Ruby code identifies which models have the `part` property and which have the `part_of`.  None of them have both.

```ruby
irb(main):001:0> [GenericWork, Image, Collection, ConferenceItem, Dataset, ExamPaper, JournalArticle, PublishedWork, Thesis].each { |desc| puts "#{desc}: #{desc
.properties.keys.grep(/^part/).inspect}"  }
GenericWork: ["part_of"]
Image: ["part_of"]
Collection: ["part_of"]
ConferenceItem: ["part_of"]
Dataset: []
ExamPaper: []
JournalArticle: ["part_of"]
PublishedWork: ["part"]
Thesis: ["part_of"]
```

As implemented, when we’re using the *OAI Mapping* the target work type (e.g. “Pulished Work”) has a `part` property, we map the *OAI ADL Record* `part_of` element to that property.  For other work types map the `part_of` element to the `part_of` property.

Likewise for *CSV Mapping*, we map `relation.isPartOf` to the `part` property for a “Published Work” and to `part` for other work types.

**Comment by jeremyf** [comment]
I've done some triage, see above, and am moving this back to "Ready for Development" as this is something that I'll want to pair with folks to work on resolving.

**Comment by KatharineV** [comment]
I think we've resolved this via conversation and changing how we input metadata.
