### ISSUE TITLE
Swap Sidekiq for GoodJob

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#344]
# Summary

Replace sidekiq with Good Job

This was done in NNP https://github.com/scientist-softserv/nnp/commit/318dcaf68dfd8456d794810e7be3517794fcc625

https://github.com/bensheldon/good_job

# Accepted Criteria
- [ ] Sidekiq has been swapped for GoodJob

# Testing Instructions
1. Manually import the following sample work: [cat_scan.pdf](https://github.com/scientist-softserv/adventist-dl/files/11233258/cat_scan.pdf)
2. via Bulkrax
   1. CSV: https://drive.google.com/file/d/1sr1XFjaeFJwMHrfk5hUmyaejHm8TVqUw/view?usp=share_link
   2. OAI:
      - `QA Note:` Diem tested this on https://sdapi.s2.adventistdigitallibrary.org. It may be worthwhile to create the OAI on a different staging tenant so that there isn't an issue with duplicate data on a tenant. Or, create the OAI import with slightly different form information
      1. `Limit`: 3
      2. `Parser`: OAI - Adventist Digital Library
      4. `Base url`: `http://oai.adventistdigitallibrary.org/OAI-script`
      5. `Metadata prefix`: oai_adl
      6. `Set (source)`: adl:issue
      7. `Visibility`: public
      8. `Rights statement`: any

- [ ] both work creation methods should successfully create a new work. If there are errors, that should be considered a different concern. What we want to look out for is whether or not good job is working to ingest them. If there are errors, that means good job is still at least trying to process them. 
- [ ] If the jobs never run, THEN we have a problem.
- [ ] **After importing a work, you should be able to go to the /jobs endpoint and see them in action + the counts of different queues. Verify works have been created once all the processing completes.** Finished jobs may look something like this: 
![image](https://user-images.githubusercontent.com/10081604/232057432-76853dcf-03f8-4598-9b07-725728013eb9.png)

**Comment by ShanaLMoore** [comment]
pro: good_job keeps track of the jobs it hasn't run, unlike sidekiq (pro: fidelity)  . Sidekiq loses it forever (pro: rapid response)

**Comment by ShanaLMoore** [comment]
@jeremyf is this one we should try to grab before the client's demo?

**Comment by ShanaLMoore** [comment]
no jobs can be running because we will remove be removing a queue. 

risk: sidekiq - while shes importing, it's more fragile thatn good jobs. if any issues occur, it just dies and we lose the job. data integrity issue. if we switch it before, will she have enough time to ingest the data?

recommendation, wait til after the board meeting (april 11th) during a window of time where there wont be any new imports.

**Comment by ShanaLMoore** [comment]
I pulled this in locally and it appears to be working. 

![Image](https://user-images.githubusercontent.com/10081604/230470914-186c26c3-01f1-46a9-bfba-7d676043803a.png)

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots and recordings.

tested on:
- work created through UI: https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/91bb399f-6aa7-442a-82b6-49405e100c46?locale=en
- Bulkrax CSV importer: https://sdapi.s2.adventistdigitallibrary.org/importers/29?locale=en
- Bulkrax OAI importer: https://sdapi.s2.adventistdigitallibrary.org/importers/30?locale=en

<details><summary>Work created through UI: jobs enqueued and completed</summary>


https://user-images.githubusercontent.com/29311858/232109563-bffb6c7b-2bd3-425b-ab28-202fb6bff1ff.mp4

![Good Job Dashboard 2023-04-14 at 8 51 12 AM](https://user-images.githubusercontent.com/29311858/232109634-e7dff148-bfb0-4a5b-baf4-1230d5ca4ecd.jpg)

</details>

<details><summary>Bulkrax CSV importer: jobs enqueued and completed</summary>

https://user-images.githubusercontent.com/29311858/232110062-59b46f26-dc07-4abf-a150-baa778c0b781.mp4

![Show Importer Adventist Digital Library 2023-04-14 at 8 55 13 AM](https://user-images.githubusercontent.com/29311858/232110081-fd71ce38-836e-405e-9404-8d214a94e78f.jpg)

</details>

<details><summary>Bulkrax OAI importer: jobs enqueued and completed</summary>

https://user-images.githubusercontent.com/29311858/232110203-55be4ea9-b24d-45c0-ae9e-cd1a3a009c6c.mp4

![Good Job Dashboard 2023-04-14 at 9 55 51 AM](https://user-images.githubusercontent.com/29311858/232110222-deb5f1bc-d6e0-4536-9485-36e54fa398e1.jpg)
</details>

**Comment by DiemBTran** [comment]
Closing bc this is not client-testable
