### ISSUE TITLE
ADL Do we need this slug fix?

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#363]
https://github.com/scientist-softserv/louisville-hyku/pull/182/files

**Comment by laritakr** [comment]
Slugs are not open-ended entry in ADL. A slug is only used if there is an aark_id, which should result in a unique slug, regardless of the text. 

Since the logic used should always result in a unique slug regardless of the title text, pluralization should not be an issue.


```
  def set_slug
    self.slug = if aark_id.present?
                  (aark_id + "_" + title.first).truncate(75, omission: '').parameterize.underscore
                else
                  id
                end
    self.slug_for_upgrade = slug
  end
```
