### ISSUE TITLE
🦄 Spike: Given IIIF Serverless Implementation, Determine Best Image Derivative Format

### ISSUE THREAD

**Issue by jeremyf** [scientist-softserv/adventist-dl#379]
The goal of this 🦄 (Research Spike) is to determine the appropriate image format for the pages we extract from a PDF.

- What are the image formats supported by IIIF Serverless?
- What are the expected resolutions for Adventist?  What can we provide as examples/prototypes for Katharine to make a decision?

Previously we had recommended PNG or JPG for storage constraints.  However in conversations with the team that may not be feasible and/or advisable due to technical constraints.

**Comment by kirkkwang** [comment]
# Findings

PTIFFs seem to only render when the user clicks and drags or resizes the image.  PNG, GIF, JP2, JPEG, and regular TIF seem to all render fine.

We used the following as our test images:
[image_formats.zip](https://github.com/scientist-softserv/adventist-dl/files/11559769/image_formats.zip)

We used the British Library staging as it is currently on a serverless configuration.

## Details

[Example work](https://mola.bl-staging.notch8.cloud/uv/uv.html#?manifest=https://mola.bl-staging.notch8.cloud/concern/generic_works/03fb72ac-97db-410b-8096-ddf4afedd6b8/manifest&config=https://mola.bl-staging.notch8.cloud/uv/uv-config.json)

For speed Pyramidal TIFF (PTIFF) and JPEG 2000 files types are recommended.  However, in our IIIF Serverless implementation PTIFFs don't seem to work smoothly.

In this example, six of the same image (but in different file types) were added to be viewed in UV.  All of them load fine except for the PTIFF.  If you click on the PTIFF you'll be met with the loading icon until you click and drag the image or zoom in/out.

### Console logs:
<img width="575" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/33face7e-7e69-4fc3-b60d-93e9c5a6297b">

Lambda link: https://jwvkwtotuzhmc4olezwhmwtqym0yrftj.lambda-url.eu-west-1.on.aws/iiif/2/5e29160ac1cf7938f1d30b903312655fd7606f92/512,0,88,398/88,/0/default.jpg

Error message: `Error: extract_area: bad extract area`

## Reference
https://training.iiif.io/iiif-online-workshop/day-two/fileformats.html

**Comment by jeremyf** [comment]
@kirkkwang what is the recommended image format we should use for images split off of a PDF?  My read is JPG, PNG, and TIF all work fine.  Is that correct?  And we can proceed with making recommendations based on storage considerations.

**Comment by kirkkwang** [comment]
JP2 preferred according to IIIF community but since we don't have that set up, I recommend JPG, or get the Lambda to play nice with PTIFF

**Comment by ShanaLMoore** [comment]
we will want @orangewolf to review this before closing.

**Comment by orangewolf** [comment]
Ptiff seems to be the obvious answer. I know that’s what Michael Klein and his team use at North Western (originators of iiif print). It’s also what Yale is using and their product lead is very involved in the IIIF spec. The Yale take was that though jp2 had been the go to, ptiff was actually better for performance and was becoming the default over time.  Can we timebox the ptiff not loading thing to 1 dev day and see if it’s fixable? Specifically I’d start by posting in the samvera channels, tagging M. Klein and seeing if anyone else has had the issue before doing any dev on it?
