### ISSUE TITLE
Remove "Share Your Work" button from homepage

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#390]
We'd like to remove the "Share Your Work" button from the homepage on all tenants. We'd like users to only be able to add works from the dashboard once they've logged in.

**Comment by KatharineV** [comment]
Can this homepage modification be applied tenant-by-tenant, or does it need to apply across the consortium? If it can be done one at a time, we prefer that. If the button must be removed for all tenants in our instance, then we will remove it from all. Thank you.

**Comment by KatharineV** [comment]
At some point the option to toggle this on/off was added to Home/Dashboard/Configuration/Features. We're able to toggle as needed. Thanks!
