### ISSUE TITLE
📚 GoodJobs Documentation

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#400]
# Summary

With the recent jump from Sidekiq to GoodJobs, the client and non-technical team members could use some help navigating how to access and use GoodJobs. It might be useful to turn this into a playbook article, for future cases

# Accepted
- [ ] A public playbook article on how to access and navigate GoodJobs is created and shared with the client

# Notes

**Comment by kirkkwang** [comment]
started a playbook article here http://playbook-staging.notch8.com/en/dev/workers/good-job/new-page/understanding-goodjob
