### ISSUE TITLE
🧹 Reconcile staging and prod differences

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#409]
# Summary
Production commits are behind staging, and we would like to reconcile this to prevent future issues. 

# Accepted Criteria
- [ ] Production env matches staging env

# Notes

**Comment by jeremyf** [comment]
Below is the list of changes:

```
❯ git slog e02ead3e~..  --no-merges
* 655d8c3 — 🎁 Adding offset to OAI parsing Jeremy Friesen, (2023-05-15)
* b2abc9c — [i359] - add local partial for date_created Shana Moore, (2023-05-09)
* 2a0c32f — [i359] - use edit field partials instead Shana Moore, (2023-05-09)
* bdca9a5 — i359 - add and update various partials to fix rendering issues Shana Moore, (2023-05-09)
* e32ed92 — Update IIIF Print Kirk Wang, (2023-05-09)
* 4b5378a — Change `peer_reviewed` to `refereed` Kirk Wang, (2023-05-02)
* d19b4bf — Adding peer_reviewed to importer and AdventistMetadata Jeremy Friesen, (2023-05-02)
* ecc1c33 — This commit will fix the rubocop errors DeonFranklin, (2023-05-05)
* 47fd330 — This commit will fix the rubocop errors DeonFranklin, (2023-05-04)
* cec5595 — Fix failing spec DeonFranklin, (2023-05-04)
* cb94ac3 — Fixed tesseract typo DeonFranklin, (2023-05-03)
* 5598695 — This commit contains the changes to the script to set records.full.each_with_index by default. DeonFranklin, (2023-04-19)
* 3d64841 — This commit contains the script for taking in oai data and exports to a csv file. DeonFranklin, (2023-04-19)
```

**Comment by jeremyf** [comment]
@KatharineV in prior iterations our standing deploy procedure was to go from SoftServ QA to Client Verification, meaning SoftServ would test things in the staging environment, if it passed, we'd then deploy those changes to production where you would verify.

However, I think we have set that approach aside for a previous approach, we go from SoftServ QA  to Client QA (in staging) which then moves to deploy to production.

What I'd like to know is what your thoughts are in regards to either approach?  I think we may have drifted in our shared understanding.

**Comment by KatharineV** [comment]
@jeremyf Thanks for the clarification. I remember now--staging was temporarily out of commission, which pushed us to test in production. If staging is available again, then I'm happy to return to the normal flow. Just let me know.

**Comment by jeremyf** [comment]
@KatharineV staging is available again, so let's proceed with the workflow you outlined.
