### ISSUE TITLE
🎁 Highlighted full text search works snippets

### ISSUE THREAD

**Issue by kirkkwang** [scientist-softserv/adventist-dl#414]
# Story

As a user, I would like to search for text found on the work and have a snippet of it displayed in the catalog search results.

# Acceptance Criteria

- [ ] Display a snippet of the text search results on the catalog search results page.

# Screenshots / Video

<details>
<summary>Example from NNP</summary>

![image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/a5016f1c-e655-4d37-9fd2-df8fddd055f5)

</details>

# Testing Instructions and Sample Files
:warning: this work requires a reindex before QA ⚠️ 

- [ ] Search for text that is on a work.
- [ ] Observe that the catalog search result displays a snippet that contains the word
- [ ] The word should be highlighted

# Notes

Ref: 
- https://github.com/scientist-softserv/adventist-dl/issues/163
- #73 

This ask seems possible, but won't really know until I dig in and try it. Looks like we would need to index the all_text_tsimv of all the file sets onto the parent work. That means if a work has 10 pages. Then it has to have all 10 pages of text indexed onto the work.

I asked Lea Ann because she did some work in NNP. Here are some GitLab links for reference (no public view unfortunately, needs Rob's log in).

https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/84/diffs
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/93
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/181/diffs
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/197/diffs
https://gitlab.com/notch8/newman-numismatic-portal/-/merge_requests/261/diffs

[NNP](https://github.com/scientist-softserv/nnp/blob/main/app/controllers/catalog_controller.rb#L113) uses file_set_text_tsimv and use these [settings](https://github.com/scientist-softserv/nnp/blob/main/app/controllers/catalog_controller.rb#L58-L67) for highlighting. For the highlighting they use this [style](https://github.com/scientist-softserv/nnp/blob/ffc20e34aa1fd62de9cbef48e1d83084da5cae09/app/assets/stylesheets/nnp-custom.scss#L3C1-L6).

**Comment by ShanaLMoore** [comment]
blocked: Reindexing works is required

**Comment by jillpe** [comment]
SofServ QA: Pass!

<details><summary>`CAT` search term</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/3f8bee58-7dff-4ec7-8a01-b0f069353b66)
</details>

<details><summary>`Floor` Search term</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/c45d9bf8-daf1-41e7-bade-343efa4a2706)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/8884ff36-5d5d-4984-85a7-7f5ca0957092)



</details>

**Comment by KatharineV** [comment]
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/1c33ee8f-6904-4fad-8ce9-01e10eb57c25)

Hooray! Tested this on ADL Staging and it worked beautifully with a [new work ](https://adl.s2.adventistdigitallibrary.org/concern/published_works/529f7a71-07af-4c1e-b005-de62726442f8?)(uploaded today via the UI) that was recently indexed.

**Comment by KatharineV** [comment]
Hi team, I just want to track something I'm seeing on production right now, so I can confirm later that it clears up. I did a search for the term "volume 17," and in the results snippets I see some highlighting that is accurate but not helpful. Link to the search: https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&search_field=all_fields&q=volume+17

Screenshot of the highlighted term: 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/31e01d78-d500-4a4d-8a93-26cca05759ae)

**Comment by KatharineV** [comment]
I'm seeing inconsistent behavior for snippets on production. It is not behaving as desired. I tested multiple terms.

- **Missing snippets**. I searched "Mollerus," and four results came back. Two are periodicals with full text. The "Item contents" fields in the [catalog search ](https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=mollerus)did NOT show snippets. Entering the work did return the keyword, and it was highlighted in the viewer. See [example ](https://adl.b2.adventistdigitallibrary.org/concern/published_works/22253193_spectrum_november_1985?locale=en&query=mollerus)and screenshots.


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/236b1524-8612-4833-9cc9-054d01de4401)
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/4e4c184e-1b4c-4cf7-82ca-ee9d1ebf5180)

I also know that the snippets will only work with items uploaded recently, so they're properly indexed. So, I tested with a [work ](https://adl.b2.adventistdigitallibrary.org/concern/published_works/22253238_spectrum_june_1996?locale=en)that was uploaded on 7/12/23. I searched for "[slaughter](https://adl.b2.adventistdigitallibrary.org/catalog?locale=en&q=slaughter&search_field=all_fields)," which appears on page 5. The work appears as the first result in the catalog search, but there is no snippet.


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/097664ae-42d2-4bab-83a4-54d774cac7f2)



- **Non-human-readable snippets**. I searched "Fall 2012" and the "Item contents" field returned a snippet with highlighting, but the place where it is reading the keyword is not meaningful. [Link to search is here](https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=fall+2012) and screenshot is below. 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/646c7e38-6c8b-4ee3-8aa5-f03e9b1c5dd2)

**Comment by kirkkwang** [comment]
Hi @KatharineV I merged a fix into staging for this issue, it does require a reindex so as soon as it gets into production I can start that.

**Comment by KatharineV** [comment]
@kirkkwang The "edit and save" workaround did solve the VPOS/WIDTH/HEIGHT snippet highlight issue on a work that I tested today. Screenshots below show the search before and after I edited and saved this [work](https://adl.b2.adventistdigitallibrary.org/concern/published_works/22253214_spectrum_august_1990). 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/6f9f6cbc-1911-4efb-a741-7f39c24ad149)
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/52bac661-2475-4ce5-8b02-d2535cc44963)

A search for "VPOS" returns 926 [results](https://adl.b2.adventistdigitallibrary.org/catalog?utf8=%E2%9C%93&locale=en&search_field=all_fields&q=%22vpos%22), so I'm not sure that I can simply look up the works with this keyword issue and force them to reindex. I may need to fix them one at a time as I find them? Not sure. Anyway, just tracking what I've learned about one aspect of the snippet highlighting.

**Comment by kirkkwang** [comment]
Ah that's way more than I thought.  I think maybe you should make a ticket to get those reindexed and we can see if we can programmatically do it.
