### ISSUE TITLE
Enable embedded YouTube videos to play

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#417]
# Summary
Adventist would like to be able to view videos sourced from a YouTube link in the UV.

# Accepted Criteria
- [ ] As a user, I can view a YouTube video in the Video Embed Viewer
- [ ] As an admin user, I can add a YouTube video link to an import and it will play for the user
 
# Note

The work types to be tested are: 
- Generic Work
- Conference Item
- Dataset
- Published Work 
- Thesis

# Testing Instructions

- [ ] Create a new work type
- [ ] Add an embed link from Youtube when creating work
- [ ] Once work is created, verify the video embed link works properly

**Comment by ShanaLMoore** [comment]
# QA RESULTS: Pass ✅ 

On [this work](https://adl.s2.adventistdigitallibrary.org/concern/generic_works/ca2b4ef1-d304-4e16-b6ab-3a1ddff48bb9?locale=en), I was able to set a video embed url to https://www.youtube.com/embed/KexI9QyBrEA

and watch the youtube video: 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/aad51a88-8a6c-4eef-844a-80d7a93d1336)

**Comment by KatharineV** [comment]
I just tested the video embed feature on the relevant work types on ADL staging. Everything works exactly as expected. Looks great! 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/e0b5df76-d207-4ff8-ad3a-b739f778cd2f)
