### ISSUE TITLE
Attached Video and Audio Support

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#418]
# Summary
Adventist would like to be able to listen/view audio and video files through the UV.

To support attached audio files in the viewer, the IIIF presentation needs to be upgraded to v3

Helpful PR: https://github.com/samvera/hyku/pull/1942 (the AV gem was contributed back to Hyku)

Accepted Criteria
- [ ] As a user, I can listen to an audio file in the Universal Viewer
- [ ] As an admin user, I can attach an audio file and it will play in the UV

**Comment by ShanaLMoore** [comment]
@DeonFranklin Are you up to giving this one a go? If you run into issues, Kirk has a lot of experience with this.

**Comment by jillpe** [comment]
Need confirmation, before proceeding, that this is still needed now that we are implementing embedded YouTube videos

**Comment by jillpe** [comment]
Per client meeting 2023-06-13, ADL is willing to use embedded YouTube videos for their audio and video files, which was taken care of in #417
