### ISSUE TITLE
🧹 Increase the size of the UV on ADL tenants so it displays pages larger upon first load, like it does on the UV example site

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#419]
# Summary
Adventist would like their UV to display it's pages like the [UV example site](https://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fwellcomelibrary.org%2Fiiif%2Fb18035723%2Fmanifest&xywh=-2437%2C-197%2C7441%2C3936)

# Accepted Criteria
- [ ] UV size on ADL tenant matches the size of the UV example site

# Testing instructions
- [ ] Observe that the UV is now 900px in height

**Comment by jillpe** [comment]
Should set up a pairing session with client on this

**Comment by kirkkwang** [comment]
I increased the height of the UV from 500px to 785px

![Image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/f950d3ca-484a-4a8a-be49-6fce204776ff)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/b9ab8a84-86c4-4e0f-aef6-f2bfdddbf3c8)

**Comment by kirkkwang** [comment]
900px for height looks good

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://sdapi.s2.adventistdigitallibrary.org/concern/datasets/b14bff8c-528a-4230-94b2-fbcf65f2fd6b?locale=en

<details><summary>The UV is 900 pixels tall</summary>

![Dataset Test IIIF Print ID b14bff8c-528a-4230-94b2-fbcf65f2fd6b Hyku 2023-05-25 at 9 49 18 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/c6d8c050-fac4-498e-8ed1-36881cf56463)
</details>

**Comment by KatharineV** [comment]
Looks good. Confirmed the UV is sized as expected in this [test ](https://sdapi.s2.adventistdigitallibrary.org/concern/published_works/7f52874c-87fc-4cda-b3fa-a22625618226?locale=en)object.

**Comment by KatharineV** [comment]
The UV is larger on production. Thank you for this improvement.
