### ISSUE TITLE
Create .csv parser for all Tenants

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/adventist-dl#42]
.

**Comment by DiemBTran** [comment]
Linked items:

Relates to:

[Epic: CSV Importer that accepts DC](https://gitlab.com/notch8/adventist-dl/-/issues/136)
#136

**Comment by DiemBTran** [comment]
Katharine Van Arsdale - March 2022

---

Most of our consortium members need to use a .csv parser for bulk upload. We need to create a parser that will work for most of our use cases so we can at least get started testing bulk uploads through methods other than OAI-PMH.

**Comment by jeremyf** [comment]
The current setup is such that all tenants use the same parsers.  So the CSV parser will be available for everyone.
