### ISSUE TITLE
🦄 Demo of embedded YouTube Link

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#421]
# Summary
Adventist wants to be able to view YouTube videos through the UV, however, an upgrade to UV v4 is required to do that. They are considering using an embedded YouTube link in the meantime, until this can happen. However, they would like to see what that would look like.

# Accepted Criteria
- [ ] A demo of an embedded YouTube link is created and presented to Adventist

**Comment by kirkkwang** [comment]
Atla has done work implementing embedded YouTube and Vimeo links
https://github.com/search?q=repo%3Ascientist-softserv%2Fatla-hyku+video_embed&type=code
