### ISSUE TITLE
🧹Epic: SDAPI collections

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#441]
# Story

After errors have been handled ref 
- #436 
- #437

per [Kirk's comment](https://assaydepot.slack.com/archives/C0311DN2YCA/p1686082652604149) we need to: 

- [x] #442

  - She has students currently using this collection for work
As an aside, we’ve assigned b1432319 as the identifier for this one which will be included on her CSV

- [x] #443

  - After reviewing it with her, all she is really interested in is the bare essentials to get them created
identifier, model, title
  - [ ] #445 

- [x] #444
  - is there a way to only import two columns so that it does not try to change the metadata? It should only run relationships. 
  - blocked need to fix majority of the errors??

  - We were looking at a way to maybe short circuit a Bulkrax import to achieve this #446 

# Acceptance Criteria

- [ ] Collections have been created in production.
- [ ] Records have established relationships with Collections in production.

# NOTES

[SDAPI_periodical_collections.xlsx](https://github.com/scientist-softserv/adventist-dl/files/11725786/SDAPI_periodical_collections.xlsx)

**Comment by ShanaLMoore** [comment]
Rob ported the re run job to prod and it is currently [running](https://b2.adventistdigitallibrary.org/jobs/jobs?locale=en&state=running). Don't start this work until that job as completed.

**Comment by jillpe** [comment]
Only last acceptance criteria is blocked until the errors are resolved
