### ISSUE TITLE
Delete all current collection, except for (as requested by Katharine) Journal of Adventist Education

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#442]
# Summary

In production, we need to delete all Collections except for the one that's titled 'Journal of Adventist Education'. 

Implementation [recommendation per Jeremy](https://assaydepot.slack.com/archives/C0311DN2YCA/p1686613373163139): 

Let's turn this into a job so that we can run it asynchronously. 

Be sure to test this locally first, to prove that it works. To do so you will want to create various Collections. Some can have 1 or 2 works attached to them to mimic production. Name one of the Collections 'Journal of Adventist Education'. 

When you run your job, all of the works should still be there and the only Collection that should remain is the one titled 'Journal of Adventist Education'.

Here is a job that you could use for inspiration. It updates the index of a collection (but we'll need to delete it instead per a given conditional): 

rake task: https://github.com/scientist-softserv/louisville-hyku/blob/main/lib/tasks/index.rake#L26-L43
calls this job: https://github.com/scientist-softserv/louisville-hyku/blob/main/app/jobs/reindex_collections_job.rb#L3

related to:
- #441 

# Acceptance Criteria

- [ ] Running the job should delete all the collections, except the one titled 'Journal of Adventist Education'.

# Testing Instructions
- [ ] developer to prove that this works by running it locally

**Comment by ShanaLMoore** [comment]
```
Collection.where(title: ['Journal of Adventist Education']).first
```

**Comment by ShanaLMoore** [comment]
#c LOCAL QA RESULTS: PASS ✅ 

## BEFORE



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/1d27713d-0852-4af9-b48a-cbf426eafdd2)

## After
```
DestroyCollectionsJob.perform_later
```
Only the Collection titled 'Journal of Adventist Education' remains.


![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/faf483b2-98e5-4836-878a-303a6dc6b56b)
