### ISSUE TITLE
Kick off a CSV import of just Collections from Katharine’s CSV

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#443]
# Summary

We need to import the csv of collections, to create the collections in production. 

related to: 
- #441 

# Acceptance Criteria

- [ ] Collections will be created after importing the [client's CSV](https://github.com/scientist-softserv/adventist-dl/issues/443#issuecomment-1589532130)

# Testing Instructions
- test locally or in staging first. take note of any errors

# Notes

original ticket details:

submit csv
review and fix failures

**Comment by jillpe** [comment]
dependent on #445

**Comment by ShanaLMoore** [comment]
[SDAPI_periodical_collections.xlsx](https://github.com/scientist-softserv/adventist-dl/files/11736503/SDAPI_periodical_collections.xlsx)
