### ISSUE TITLE
Lastly, will need to create the relationships between the records and collections

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#444]
# Summary

1. Per Katharine, she needs our help to create the spreadsheet of relationships. 

  Kirk has all of the OAI data locally, in CSV files. We will need to create a spreadsheet with records referencing their collection's identifier, in the parents column. 

2. Additionally, consider optimizing how we can import relationships only #446 
- [WIP concept](https://github.com/samvera-labs/bulkrax/pull/817)

# Acceptance Criteria

- [ ] Importing this CSV should establish relationships between pre-existing works and collections. 

# Testing Instructions

- recreate a similar scenario and test locally. 
- verify that the relationship has been formed after import. 

# Notes

original ticket details: 

Disregard records with errors. 
get count of how many errors remain. 

consult with katharine to determine next steps.

**Comment by ShanaLMoore** [comment]
cc @jillpe 

Ask Katharine for a CSV to represent the records/collection relationships.
CSV will have all the records with a parents column. The parents column should have the identifier of the collection it belongs to.
So in total, CSV will need an identifier, model, title and parents column for each record.

**Comment by ShanaLMoore** [comment]
[tldr; Katharine needs help creating this CSV](https://assaydepot.slack.com/archives/C0313NJV9PE/p1686591452998309)

**Comment by kirkkwang** [comment]
CSV for relationships:

Preview:



identifier | work_type | title | parents
-- | -- | -- | --
13128988 | JournalArticle | $0.13 postage stamp convert | b1412549b
13128989 | JournalArticle | $1 million Bible ministry makes major impact | b1304841
13128990 | JournalArticle | $1 million for Reading Hospital | b1304841
13128991 | JournalArticle | $1 million grant | b1458775
13128992 | JournalArticle | $1 million in tithe reached by one church | b20000064
13128993 | JournalArticle | $1,000.00 flowers for Investment | b2920322
13128994 | JournalArticle | $1,400 raised for Mayor's Appeal | b20000094
13128995 | JournalArticle | $1.275 million to South America | b1304841
13128996 | JournalArticle | $1.3 million grant to hospital | b1304841
13128998 | JournalArticle | $1.98 fingernails | b22255542
13128999 | JournalArticle | $10,000 awarded to AUC students | b1415927
13129000 | JournalArticle | $10,000 witness | b1304841
13129001 | JournalArticle | $100 a shingle | b1630893
13129002 | JournalArticle | $100,000 handshake | b1424608
13129003 | JournalArticle | $100,000 presented to Vancouver Church | b1471399
13129004 | JournalArticle | $100,000 raised for women in ministry | b1458775
13129005 | JournalArticle | $100,000 to educate pastors in Russia | b1486202
13129006 | JournalArticle | $100,000 vote of confidence | b1415927
13129007 | JournalArticle | $100,000 voted for lay evangelism in MAUC | b1486202
13129008 | JournalArticle | $1000 investment reaches &3 million business | b1486202



https://drive.google.com/file/d/17dwiZpYQx6wqTznJzRmHsUSHJ0409ltj/view?usp=sharing

**Comment by ShanaLMoore** [comment]
WIP concept PR: https://github.com/samvera-labs/bulkrax/pull/817

**Comment by ShanaLMoore** [comment]
this job is currently running in production
