### ISSUE TITLE
Fix solr uri string too long error

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#445]
# Story
Uploading collections for Adventist SDAPI broke several views with due to solr query errors.

# Testing instructions

Import a large number of collections using SDAPI collection csv 
[SDAPI_periodical_collections_updated.csv](https://github.com/scientist-softserv/adventist-dl/files/11736114/SDAPI_periodical_collections_updated.csv)

Verify that dashboard views open:
- [ ] my collections
- [ ] all collections
- [ ] my works
- [ ] all works

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshots.

tested on:
- importer: https://sdapi.s2.adventistdigitallibrary.org/importers/60?locale=en
- My Collections: https://sdapi.s2.adventistdigitallibrary.org/dashboard/my/collections?locale=en
- All Collections: https://sdapi.s2.adventistdigitallibrary.org/dashboard/collections?locale=en
- My Works: https://sdapi.s2.adventistdigitallibrary.org/dashboard/my/works?locale=en
- All Works: https://sdapi.s2.adventistdigitallibrary.org/dashboard/works?locale=en

<details><summary>The importer imported 243 collections. After that import, I can still access my/all works/collections pages</summary>

![Collections 2023-06-20 at 4 11 01 PM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/ee9245a6-ae84-4f79-93d9-c37b2c6cc1f5)
![Collections 2023-06-20 at 4 11 09 PM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/6947dcc8-f4c5-45d1-a65d-49235880bf61)
![Works 2023-06-20 at 4 11 18 PM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/b0498acd-2e14-4437-9004-90c0314139d5)
![Works 2023-06-20 at 4 11 27 PM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/cce37c5b-8feb-48a4-b962-d87516b9c78f)
</details>
