### ISSUE TITLE
Investigate the 20 records that did not import successfully

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#462]
Found 20 identifiers that may needs examining

- [x]   "13344634",
- [ ]   "13344709",
- [ ]   "13345109",
- [ ]   "13345146",
- [ ]   "13345153",
- [ ]   "13345464",
- [x]   "13345604",
- [ ]   "13345606",
- [ ]   "13408798",
- [ ]   "13408935",
- [ ]   "13420430",
- [ ]   "13435919",
- [ ]   "13435919",
- [ ]   "13457012",
- [ ]   "13502474",
- [ ]   "13502692",
- [ ]   "14143783",
- [ ]   "14785296",
- [ ]   "14785317",
- [ ]   "14785582",
- [ ]   "14785586"

And it looks like the 20 records already exist in the system.

1. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13344634_markers_identify_sites_of_historical_significance
2. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345109__part_of_the_program_just_not_in_sales
3. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345146_sugar_for_a_chicken
4. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345153_texas_justice
5. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345464_look_at_the_stars
6. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345604__blind_me_lord
7. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345606_the_beauty_of_good_sense
8. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13408798_sow_1_billion_campaign_launched_with_billboards_and_cards
9. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13408935_touch_a_heart_tell_the_world_a_ministry_for_every_woman
10. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13420430_god_and_good_guys
11. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13435919_sermon_in_shoes
12. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13457012__we_have_seen_his_star
13. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13502474_strange_is_good
14. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13502692_trading_in_the_good_life_for_the_exchanged_life
15. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/14143783_love_still_matters_most
16. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/14785296_wa_conference_first_to_provide_assistive_listening_equipment
17. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/14785317_ministry_retreat
18. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/14785582_healing_from_war
19. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/14785586_paces_a_perfect_fit
20. https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13345464_look_at_the_stars

**Comment by laritakr** [comment]
"id":"13344634_markers_identify_sites_of_historical_significance",
        "identifier_tesim":["13344634",
          "3344634"],
        "fedora_id_ssi":"ca279154-fb23-4915-913e-53f1893f0b15"

        "id":"13344709_chesapeake_students_lend_a_hand_in_the_bahamas",
        "identifier_tesim":["3344709",
          "13344709"],
        "fedora_id_ssi":"94cf1d90-7916-4425-83c0-7b1bc5fa8d8e"

        "id":"13345109__part_of_the_program_just_not_in_sales",
        "identifier_tesim":["13345109",
          "3345109"],
        "fedora_id_ssi":"5e1eb845-d479-4397-89f2-bd0684bd714f"}

         "id":"13345146_sugar_for_a_chicken",
        "identifier_tesim":["13345146",
          "3345146"],
        "fedora_id_ssi":"010ccff2-3a36-4149-81cb-8224fca932bb"

        "id":"13345153_texas_justice",
        "identifier_tesim":["13345153",
          "3345153"],
        "fedora_id_ssi":"c3d930fb-1ef4-4aa4-a489-c8113ae31caf"

        "id":"13345464_look_at_the_stars",
        "identifier_tesim":["13345464",
          "3345464"],
        "fedora_id_ssi":"796410d7-ec9f-4890-968f-96de723935c6"

        "id":"13345604__blind_me_lord",
        "identifier_tesim":["3345604",
          "13345604"],
        "fedora_id_ssi":"325c96ff-bec5-4713-8a38-9a7264c93dc8"

        "id":"13345606_the_beauty_of_good_sense",
        "identifier_tesim":["13345606",
          "3345606"],
        "fedora_id_ssi":"b23d6916-b62a-49d3-976a-3009ecab0f30"

        "id":"13408798_sow_1_billion_campaign_launched_with_billboards_and_cards",
        "identifier_tesim":["13408798",
          "3408798"],
        "fedora_id_ssi":"5b91504a-8a80-4a00-ae05-f2b90af752c2"

        "id":"13408935_touch_a_heart_tell_the_world_a_ministry_for_every_woman",
        "identifier_tesim":["13408935",
          "3408935"],
        "fedora_id_ssi":"bb2e17bb-1c6e-4411-a85c-370f96036816"

        "id":"13420430_god_and_good_guys",
        "identifier_tesim":["3420430",
          "13420430"],
        "fedora_id_ssi":"a1fb15f8-233d-4b6e-b475-1388f8d0ef0b"

        "id":"13435919_sermon_in_shoes",
        "identifier_tesim":["13435919",
          "3435919"],
        "fedora_id_ssi":"6de54c83-3796-4700-8419-468c2b7b1de3"

        "id":"13457012__we_have_seen_his_star",
        "identifier_tesim":["13457012",
          "3457012"],
        "fedora_id_ssi":"c495891e-2ebe-4365-96fe-74c1a80faac1"

        "id":"13502474_strange_is_good",
        "identifier_tesim":["13502474",
          "3502474"],
        "fedora_id_ssi":"aed4d721-d4fa-447f-99f2-138e450513dd"

        "id":"13502692_trading_in_the_good_life_for_the_exchanged_life",
        "identifier_tesim":["13502692",
          "3502692"],
        "fedora_id_ssi":"20f8a1f9-a7a0-403e-b6cc-825f00a362ac"

        "id":"14143783_love_still_matters_most",
        "identifier_tesim":["4143783",
          "14143783"],
        "fedora_id_ssi":"8f3703e9-8575-4e26-bdd2-c9f34b636068"

        "id":"14785296_wa_conference_first_to_provide_assistive_listening_equipment",
        "identifier_tesim":["14785296",
          "4785296"],
        "fedora_id_ssi":"fbd98ab8-c177-465b-b292-36ff5bffe1ab"

         "id":"14785317_ministry_retreat",
        "identifier_tesim":["4785317",
          "14785317"],
        "fedora_id_ssi":"0b87c2c3-7e1c-4b27-8400-b7be0b379e9f"

        "id":"14785582_healing_from_war",
        "identifier_tesim":["14785582",
          "4785582"],
        "fedora_id_ssi":"465531c6-e1e5-4982-b4d3-13e77e885d6e"

        "id":"14785586_paces_a_perfect_fit",
        "identifier_tesim":["14785586",
          "4785586"],
        "fedora_id_ssi":"93764e85-7b76-4824-b1f6-b9faa7c787b0"

**Comment by laritakr** [comment]
It appears that this has resolved the problem. 5 of the rerun import jobs completed and appear to have run normally… 15 are left in the queue. One of the 5 completed works is [this one](https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13344634_markers_identify_sites_of_historical_significance?locale=en). 

It is apparently just a matter of time for these to complete now.

**Comment by ShanaLMoore** [comment]
job successfully completed
