### ISSUE TITLE
Search then paginate does not work

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#469]
# Summary
When you search in the catalog, then try to paginate, it errors out. This seems to happen only after you search for something. If you do an empty search the pagination is fine. 

<details><summary>example</summary>

https://github.com/scientist-softserv/adventist-dl/assets/84697174/3b48b5d3-2ced-4204-9985-dcc20395d5b4

</details>

# Accepted Criteria
- [ ] Pagination does not error out upon a search in the catalog

# Testing Instructions
Recreate the search for FLOOR in ADL staging, and paginate to page two. Verify that pagination resolves correctly.

**Comment by ShanaLMoore** [comment]
This is a weird one. 

This only seems to be happening on staging, and with the specific word "floor". I randomly searched for other words like 'index' and 'cat' and am able to paginate just fine. 

Searching for the word floor in prod is fine. 

https://share.getcloudapp.com/lluX2gye

**Comment by laritakr** [comment]
Related to ticket https://github.com/scientist-softserv/adventist-dl/issues/470.

The problem is due to a work with 5 snippets attempting to render on the catalog page (it was on page 2, so that's why pagination triggered the issue).

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screen recording.

tested on:
- search query: https://adl.s2.adventistdigitallibrary.org/catalog?locale=en&q=floor&search_field=all_fields

<details><summary>Search and pagination works for term "floor"</summary>

https://github.com/scientist-softserv/adventist-dl/assets/29311858/601b0e9f-e17f-4df5-a545-5ffea78e2cfe
</details>

**Comment by DiemBTran** [comment]
does not require client QA
