### ISSUE TITLE
⚙ Verify use of graph_indexer

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#473]
# Summary 

We were unable to delete 20 collections during the SDAPI ingest.  It is because Adventist is not using hyrax-v2_graph_indexer, and large collections were failing due to the nested indexing.

Pull in this [commit](https://github.com/scientist-softserv/adventist-dl/pull/448/commits/3f0ccc80ce700d49283eaa7f32a9901ca61d4e48) into main for the fix.

# Acceptance Criteria

- [ ] The gemfile lock contains the above commit

# Screenshots or Video

# Testing Instructions

⚠ QA by dev ⚠ 
- Go into the server and verify the following method is coming from the graph indexer
 ```
Collection.first.method(:before_update_nested_collection_relationship_indices)
```
  
# Notes

**Comment by laritakr** [comment]
Waiting for https://github.com/scientist-softserv/hyrax-v2_graph_indexer/pull/1 to be merged, or ideally a new version released.

**Comment by ShanaLMoore** [comment]
this task will be completed as part of https://github.com/scientist-softserv/adventist-dl/issues/468

**Comment by ShanaLMoore** [comment]
![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/0c5cd2fa-dd32-4edc-88e1-5178ffa4893c)

should be coming from `hyrax-v2_graph_indexer-ec2329120dd4/lib/hyrax/v2_graph_indexer.rb:54> `instead

**Comment by ShanaLMoore** [comment]
QA RESULTS: Pass ✅ 
This does not require client review. 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/a3616d89-63be-48b8-b315-5566de2a4494)
