### ISSUE TITLE
🐛 OCR search count

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#477]
# Summary

Sometimes when you search for words with matches, the UV reports way more matches than is present. The following example should be 3:

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/42129b38-62ee-4c89-81fc-c3de108c515b)

Kirk implemented a fix but it was against Derivative Rodeo: https://github.com/scientist-softserv/derivative_rodeo/pull/34/files

This ticket is to...
1) pull this fix into iiif_print AND/OR
2) Make sure this works after ADL gets derivative rodeo. (for future users is derivative rodeo a dependency of iiif_print? if not, maybe the fix belongs in iiif_print instead)

# Acceptance Criteria

- [ ] An appropriate count should return when a user perform a UV search that has a match

# Screenshots or Video

# Testing Instructions

- [ ] create a new work with the classic car scan image
- [ ] search for the word `minute`
- [ ] note that there should only be one result

# Notes

Update no-rodeo branch with this fix and/or

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://sdapi.s2.adventistdigitallibrary.org/concern/images/1304b066-0d54-42a0-afa8-cfb85be10f11?locale=en
- file: 
[cat_scan.pdf](https://github.com/scientist-softserv/adventist-dl/files/12072372/cat_scan.pdf)

<details><summary>There is only 1 match for the word "minute"</summary>

![Image 2023-07-11 🐛 OCR search count #477 ID 1304b066-0d54-42a0-afa8-cfb85be10f11 Hyku 2023-07-17 at 10 46 28 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/6232bac9-8488-459e-b669-762aecdf70d7)
</details>

**Comment by DiemBTran** [comment]
closing as an internal issue (doesn't live on another project board)
