### ISSUE TITLE
🐛 Revert to main branch of IiifPrint

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#483]
# Story

Revert to use IiifPrint main branch.

**Background:** Derivative Rodeo refactoring of IiifPrint broke PDF splitting. Branch `no_rodeo` was swapped as a temporary fix. Two pull requests to IiifPrint fixed PDF splitting and brought in subsequent patches as well.

- https://github.com/scientist-softserv/iiif_print/pull/256
- https://github.com/scientist-softserv/iiif_print/pull/257

# Acceptance Criteria

- [ ] IiifPrint is updated to use branch `main`
- [ ] PDF splitting performs appropriately

# Screenshots / Video

<details>
<summary></summary>

![Screenshot 2023-07-06 at 2 02 28 PM](https://github.com/scientist-softserv/adventist-dl/assets/17851674/68acb8e5-339a-4f02-8ec5-188419108998)
</details>

# Testing Instructions and Sample Files

Create a new work using file 
[iiif-print-test.pdf](https://github.com/scientist-softserv/adventist-dl/files/11970883/iiif-print-test.pdf)

Verify that the job completes normally and PDF is split into pages and viewable.

# Notes
Move ticket to complete following SoftServe QA.

**Comment by DiemBTran** [comment]
**This passes SoftServ QA:** See attached screenshot.

tested on:
- https://s2.adventistdigitallibrary.org/jobs/jobs?locale=en&state=running
- https://sdapi.s2.adventistdigitallibrary.org/concern/images/88c00ed6-83cc-4fe1-830d-9f6997be4c31?locale=en
- [iiif-print-test.pdf](https://github.com/scientist-softserv/adventist-dl/files/12005655/iiif-print-test.pdf)

<details><summary> pdf splits and is viewable</summary>

![Image 2023-07-10 pair with LaRita ID 88c00ed6-83cc-4fe1-830d-9f6997be4c31 Hyku 2023-07-10 at 11 58 51 AM](https://github.com/scientist-softserv/adventist-dl/assets/29311858/396cd353-77b9-4f68-87f5-e1e6abea911f)

</details>
