### ISSUE TITLE
SDAPI: Editing or creating a new work in prod results in 504 Gateway Time-out

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#505]
For the last few weeks, every time we edit or create a new work in SDAPI production, when we try to save the work it takes a long time and results in a 504 Gateway Time-out and the changes do not save. Basically, we can't edit or create works in this tenant right now. 

[Example work](https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/13209383_law_love_grace_a_commentary_on_the_first_quarter_1982_sabbath) I have tried to edit several times. It is missing a related URL and the source is incorrect (should be Seventh-day Adventist Periodical Index, not obituary). I've entered the URL into the related field and I've updated the source several times. Every attempt to save results in the 504 Gateway Time-out and the changes are not present. 

Screenshots below show the errors, my attempt to change the metadata and save, and the gateway timeout. You can visit the work page to see that the errors are still present. 

URL I'm trying to add: http://documents.adventistarchives.org/Periodicals/LUH/LUH19820119-V74-02.pdf#page=9 

Correct Source: Seventh-day Adventist Periodical Index

![Image](https://user-images.githubusercontent.com/118196520/256561687-d5ba12de-07cd-4852-a133-ba677da86fae.png)

![Image](https://user-images.githubusercontent.com/118196520/256561920-1f5106e1-be84-4970-93cd-523d1d9c5d84.png)

![Image](https://user-images.githubusercontent.com/118196520/256560942-53466f53-f9bf-4946-9b0b-8e1eefe683c3.png)

**Comment by KatharineV** [comment]
Tried to create a new Journal Article work on prod today, and it did not save. I got a 504 Gateway Time-out. Looks like we can't do much of anything new on https://sdapi.b2.adventistdigitallibrary.org/ for now.

**Comment by ShanaLMoore** [comment]
I can successfully create/edit a work in the adl prod tenant. I verified that I cannot do the same in sdapi. 

Additionally I noticed that when you click to add a new work, the modal of options do not pop up like they do in staging. 

# STAGING
![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/1bbc85a3-db5d-407b-8172-d10c38861b04)

# PROD
![Screen Recording 2023-08-02 at 07 26 57 AM](https://github.com/scientist-softserv/adventist-dl/assets/10081604/a37e6d7d-e2bf-452a-b314-5cffa2a1fe17)

**Comment by ShanaLMoore** [comment]
When I pulled down the sha (44340e9d) in prod to run locally, I am able to see the modal.

**Comment by KatharineV** [comment]
@ShanaLMoore yes, sorry about the confusion about work types on SDAPI prod. I did turn off the other types so students working on the tenant would have an easier time adding new works.

**Comment by ShanaLMoore** [comment]
Restarting fedora resolved this issue. It should be good now! 

I was able to created 4 works and a test collection (all should have my name in the title). 

cc @KatharineV 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/89b79653-e4e7-476e-b162-c035128e16b3)

**Comment by KatharineV** [comment]
@shana Amazing! Thank you so much!!!
