### ISSUE TITLE
CSV import with remote files stuck pending?

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#532]
Today I tested a CSV import via Bulkrax with minimal metadata and a link to a file on S3. I wanted to see how a CSV import works with remote files rather than a ZIP. The test I did on ADL Staging has been pending for over an hour. Did I do something wrong or is it stuck? Your insight will be gratefully received! Thanks.

https://adl.s2.adventistdigitallibrary.org/importers/30?locale=en

**Comment by kirkkwang** [comment]
Looks like we need a column for `work_type` with whatever work type, which is interesting because I thought it would have just defaulted to `GenericWork` 🤔 .

<img width="1255" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/02bc077e-b20c-4f99-b09f-bb8ce6752c18">

In any case, it looks like the way it's set up, it will just map the text of the `remote_url` column on the csv to the `remote_url` property.

**Comment by ShanaLMoore** [comment]
I'm glad it was just a data issue but it would be helpful for bulkrax to capture the issue though instead of silently staying pending. I'll file an issue against bulkrax.

**Comment by KatharineV** [comment]
Thanks for checking the failed importer from last month. I created a new one today using a CSV with all the required fields **plus **  work_type, and the importer was successful. The Samvera Bulkrax [documentation ](https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#files-location)that I've been using as a reference doesn't list work_type as a required field, so is this a bug or is the field actually required and the documentation needs an update?

**Comment by kirkkwang** [comment]
Thanks Katharine, i'll check with the team about if that is expected behavior, either way it should throw an error instead of having it stuck in pending.  But I'm at least glad we have a workaround for now.

**Comment by KatharineV** [comment]
Kirk, can you or the team tell me if this kind of remote file URL should work to import a PDF to hyku?

https://www.andrews.edu/library/car/cardigital/Periodicals/Adventist_Journey/2021/2021_07_08.pdf

It's a link to an open file share rather than S3.

**Comment by KatharineV** [comment]
Awesome, thank you. I'll make sure we always include work_type. Also, I was definitely confused about the related vs. remote URL. I just tried that link with the proper heading (thanks!) and it [imported ](https://sdapi.s2.adventistdigitallibrary.org/importers/70?locale=en)the work on staging with no issues. So, I think it's ok to close this ticket, and I will.
