### ISSUE TITLE
Contribute back to Hyku and Switch to Hyku main

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#539]
## Summary
Goal: By end end of this work, we should be using Hyku main. 

This would mean that any non-specific adventist fixes should be contributed back to Hyku main. 

## Accepted Criteria
- [ ] PRs for Hyku fixes created
- [ ] Adventist Knapsack uses Hyku main instead of the adventist_dev branch

## Testing Instructions

**Comment by jeremyf** [comment]
I'm not seeing how this is actionable.  It strikes me as a reminder of how to proceed.

**Comment by ShanaLMoore** [comment]
@jeremyf I believe the purpose of this ticket was to contribute back anything necessary to Hyku main so that we can ultimately switch adventist_knapsack to main as one of the final steps of this work. I will update the description.

**Comment by ShanaLMoore** [comment]
Hyku main would introduce a significant amount of changes now that it includes pals contributions + and upgrade to hyrax5.  Team Violet agrees that we should not do this right now, as it may introduce too many changes and require the client to re QA everything.
