### ISSUE TITLE
Hide contents of masked collections

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#54]
# Summary
Adventist would like the ability to hide contents of collections the end user doesn't want or need to see. 

Example: We have a collection called "genre:book" that the end user doesn't want or need to see

# Acceptance Criteria

- [ ] Ability to hide contents of collections

# Notes

Confused how to fill this out? Check out the [playbook](https://playbook-staging.notch8.com/en/notch8/process/issues)

**Comment by DiemBTran** [comment]
Katharine - Oct 2022

---

Hey folks, I think I may have misspoken earlier. We do need the ability to change collection visibility, but the works within the collection can stay visible. We can use the existing visibility settings in Hyku to modify collection contents as needed. I think this ticket is based on my misunderstanding of some Hyku features that I understand better now. We could close this ticket and ignore the request...unless I'm missing something. I don't want to close the ticket without confirming with [@jillkp](https://github.com/jillkp) who created it for me.

**Comment by jillpe** [comment]
Closed - confirmed we no longer need this ability
