### ISSUE TITLE
🦄 SPIKE: do all the decorators get loaded properly (probably need to check most or all of them)

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#548]
# Story

Verify: do all the decorators get loaded properly? (probably need to check most or all of them)

Check where it is defined - is it coming from the decorator or not

# Acceptance Criteria

- [ ] Confirm if all the decorators get loaded properly. Put the implementation fix in another ticket.

# Screenshots / Video

<details>
<summary></summary>

</details>

# Testing Instructions and Sample Files

-

# Notes

- [ ] #560

**Comment by kirkkwang** [comment]
- [ ] app/indexers/app_indexer_decorator.rb
- [ ] app/indexers/collection_indexer_decorator.rb
- [ ] app/jobs/create_derivatives_job_decorator.rb
- [ ] app/jobs/import_url_job_decorator.rb
- [ ] app/matchers/bulkrax/application_matcher_decorator.rb
- [ ] app/models/content_block_decorator.rb
