### ISSUE TITLE
:bug: Other resources page should load

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#556]
# Story

A user should be able to click "Other resources" from the tenant's home page, and be directed to /resources.

# Acceptance Criteria

- [ ]

# Screenshots / Video

<details>
<summary>STAGING</summary>

link: https://adl.b2.adventistdigitallibrary.org/resources?locale=en

<img width="1339" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/10081604/48ecd08d-bb05-48d9-a06f-c5c6915eb9cc">

</details>

# Testing Instructions and Sample Files

-

# Notes

**Comment by ShanaLMoore** [comment]
causes 500 errors in staging

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/7343b909-a854-4641-aec6-41b4b920020a)

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

Clicking `Other Resources` on the tenant home page directs the user to https://demo.adventist-knapsack-staging.notch8.cloud/resources?locale=en



![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/a33c0cc3-7d4b-42e0-ba9b-5b0130106268)
