### ISSUE TITLE
:bug: require iiif_print/iiif_print causes error

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#561]
When running the app locally and visiting hyku.test I received this error: 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/e2dd853f-1279-44a3-be32-968727f50ff5)

<img width="430" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/10081604/fa849d25-8715-4967-9ec9-6f800afad832">

**Comment by ShanaLMoore** [comment]
This was removed because it was disruptive to our workflow and iiif_print was being included in iiif_print.scss, do we need to bring it back?

**Comment by laritakr** [comment]
I believe it is already required in hyku, so it shouldn't be needed in the knapsack.
