### ISSUE TITLE
🦄 SPIKE: Test Bulkrax

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#569]
Ferify that bulkrax Import/export functionality matches adventist proper behavior. 

A user should be able to import works and files using their bulkrax options:

- [x] CSV parser
- [x] OAI parser

**Comment by ShanaLMoore** [comment]
Good job doesn't appear to run when attaching a work.

**Comment by ShanaLMoore** [comment]
# CSV PARSER

**Comment by ShanaLMoore** [comment]
# OAI Parser ✅ 

link: https://demo.adventist-knapsack-staging.notch8.cloud/importers/1?locale=en#work-entries

I was able to import 100 articles using the OAI parser. 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/aa097145-e802-45f4-bac5-e0d290ec3603)

**Comment by ShanaLMoore** [comment]
![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/583d5545-1e77-4071-bd94-590447f174df)

**Comment by ShanaLMoore** [comment]
there should be a link to the work from the importer: 

Example from adventist production

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/8daaa91b-77ba-4d23-9ccb-ab3bfc97758e)

**Comment by jillpe** [comment]
SoftServ QA: 

[CSV Importer](https://demo.adventist-knapsack-staging.notch8.cloud/importers/45?locale=en)

[OAI Importer]()

**Comment by ShanaLMoore** [comment]
# QA Results: Pass ✅ 

The reported issues seems to be ok now. 

I successfully created a [CSV](https://demo.adventist-knapsack-staging.notch8.cloud/importers/115?locale=en) and [OAI](https://demo.adventist-knapsack-staging.notch8.cloud/importers/116?locale=en) importer. Work entries are visible.
