### ISSUE TITLE
🐛 Good Jobs should process jobs

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#571]
# Summary
When I manually create a work via the UI and attach a file, I don't see jobs running in good_job. The work never attaches the file I selected. 

# Acceptance Criteria
- [ ]  Good jobs should run background jobs

# Testing Instructions
- create a manual work. attach a file to it. 
- visit /jobs endpoint to confirm the counts are zero in the scheduled and running queues (meaning that the jobs have finished processing). It should take a few minutes.
- refresh the work's show page to confirm that the file got attached. 

# Screenshots

<img width="1352" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/10081604/de6a565e-96ef-4a13-a035-807de2293555">

**Comment by ShanaLMoore** [comment]
good_job doesn't appear to queue anything up when creating a work

**Comment by ShanaLMoore** [comment]
When initiating the index rake task: 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/8883c6f6-d9b9-4da5-85b9-c9b40bbc3590)

But GoodJob::Job.count => 0

**Comment by ShanaLMoore** [comment]
disregard the above comments, I may have forgotten to switch tenants in the console. Trying again: 

`bundle exec rails index_works => Enqueued ReindexWorksJob (Job ID: 3277628f-9c3b-406f-9fd8-fbdab2540025) to GoodJob(default)`

`GoodJob::Job.count => 1`

`GoodJob::Job.find_by(active_job_id: "3277628f-9c3b-406f-9fd8-fbdab2540025") => #<GoodJob::Job id: "737a71c4-cd61-47f8-9527-2f4e9c91c4c3", queue_name: "default", priority: 0, serialized_params: {"job_id"=>"3277628f-9c3b-406f-9fd8-fbdab2540025", "locale"=>"en", "tenant"=>"5f5840c0-f5c1-41d1-bd0f-ecc2b400f62d", "priority"=>0, "arguments"=>[], "job_class"=>"ReindexWorksJob", "executions"=>0, "queue_name"=>"default", "provider_job_id"=>nil}, scheduled_at: nil, performed_at: nil, finished_at: nil, error: nil, created_at: "2023-09-27 18:04:45", updated_at: "2023-09-27 18:04:45", active_job_id: "3277628f-9c3b-406f-9fd8-fbdab2540025", concurrency_key: nil, cron_key: nil, retried_good_job_id: nil, cron_at: nil> `

**Comment by ShanaLMoore** [comment]
cleared all the jobs to re orient myself. I kicked off a bulkrax importer and can see this in the terminal but nothing in the dashboard still

```ruby
 #<GoodJob::Job id: "184a77a2-b5de-41bf-a731-6a4243c04c69", queue_name: "import", priority: -20, serialized_params: {"job_id"=>"be969512-855e-4759-b1bc-a67603656b43", "locale"=>"en", "tenant"=>"5f5840c0-f5c1-41d1-bd0f-ecc2b400f62d", "priority"=>-20, "arguments"=>[2, false], "job_class"=>"Bulkrax::ImporterJob", "executions"=>0, "queue_name"=>"import", "provider_job_id"=>nil}, scheduled_at: nil, performed_at: nil, finished_at: nil, error: nil, created_at: "2023-09-27 19:41:00", updated_at: "2023-09-27 19:41:00", active_job_id: "be969512-855e-4759-b1bc-a67603656b43", concurrency_key: nil, cron_key: nil, retried_good_job_id: nil, cron_at: nil>
```

**Comment by ShanaLMoore** [comment]
Switched env var to sidekiq just to see if it'll work. 

It immediately queued in the dashboard as expected. I attached a file to a work via the UI. 

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/de35ae77-24b3-47f5-b0db-3bbda8bd66a8)

But an error occurred: 
![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/4ad6f1c6-acdd-4892-a3c7-be834b65b0d0)

**Comment by ShanaLMoore** [comment]
I haven't been able to figure this out yet so I'm going to move it back and pick up another ticket for the sake of progress.

**Comment by ShanaLMoore** [comment]
Reading through the good_jobs doc, this seems to describe the behavior I'm seeing
```
:external causes the adapter to enqueue jobs, but not execute them. When using this option (the default for production environments), you'll need to use the command-line tool to actually execute your jobs.
```

I changed external to inline. It successfully attached the work but uses the rails server instead so I'll keep trying other configurations and/or try to figure out why external works for adventist locally but not for this project.



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/e7f2060e-6e4a-4ed7-a323-4cf2b68a7cea)

**Comment by laritakr** [comment]
@ShanaLMoore is this one done now?

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

- Was able see the jobs running and scheduled when creating a work
- Watched the jobs complete
- File was attached to [work's show page](https://demo.adventist-knapsack-staging.notch8.cloud/concern/journal_articles/95442716-8b1f-464d-b63c-766bb58f75e5?locale=en)


<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/036b0f70-7944-4139-879d-3c843d999e0b)



</details>
