### ISSUE TITLE
Action buttons arent available on Work show page

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#572]
# Adventist Staging

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/ac0f43ea-c917-4d74-aa8a-1dd3f98add0b)

# Locally

![image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/a55e6317-5036-4281-af46-086c487da3ab)

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

[Work URL](https://demo.adventist-knapsack-staging.notch8.cloud/concern/journal_articles/record_spd_2023_06_17_10_11__romantic_cruises_under_tropic_skies_1950_195?locale=en)
- Buttons present: edit, delete, file manager, attach child, add to collection, feature



![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/5b3693c6-b2c8-4b65-b2a8-e7c7eb72f40d)
