### ISSUE TITLE
Admin Set show page is broken

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#578]
![Image](https://github.com/scientist-softserv/adventist-dl/assets/17851674/5ac8caf8-0f96-443f-b825-b354a9857616)

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

https://demo.adventist-knapsack-staging.notch8.cloud/admin/admin_sets/fab03ed6-3a04-413f-814a-23169795ab69?locale=en

![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/518a8156-3d82-451a-9dd0-7f9f5d49bcf4)
