### ISSUE TITLE
Collection branding banner doesn't work

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#580]
Logo & link work. Banner image does not.

![Image](https://github.com/scientist-softserv/adventist-dl/assets/17851674/b71d1f5f-16e4-4dc7-b3a5-7d902d679bc4)

**Comment by kirkkwang** [comment]
looks like this is a problem even on staging, maybe we can kick this one down the road?


![Image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/565e30d9-eea5-4c03-bc72-410b752a968b)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/df578b49-0aee-418e-b053-5ab280fb2099)

**Comment by ShanaLMoore** [comment]
Since this is an issue in staging I'm going to kick this one out of this sprint as it wasn't something impacted by the knapsack work.

**Comment by KatharineV** [comment]
Maybe this wasn't broken by Knapsack, but it definitely used to work. See https://github.com/scientist-softserv/adventist-dl/issues/35 and screenshot of working banner on Prod last year.



![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/eca9089f-1a3e-49ec-97f4-20c21c242a52)
