### ISSUE TITLE
Creating a new User Collection causes error

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#583]
## Summary
When creating a `User Collection` through the Dashboard (`Dashboard` -> `Collections` -> `Add New Collection` -> `User Collection`), it results in an error

![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/b37f65c9-9d7a-44e4-9d09-0a5415f4679e)

## Accepted Criteria
- [ ] As a user I can create a user collection and it saves

**Comment by kirkkwang** [comment]
I see a different error, but this error specifically should have been fixed, can you do a `git pull` and then try again?  I see this one 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/25b02c69-647a-4795-aa4b-482465622976)

**Comment by kirkkwang** [comment]
After restarting my server it fixed itself
