### ISSUE TITLE
Create an image work type error

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#586]
## Summary
When trying to create an image work type through the dashboard, it results in an error

![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/0b82e8e5-0b61-4ac4-9c26-02cb59bbf783)

## Accepted Criteria
- [ ] As a user I can create an image work type through the dashboard and it saves

**Comment by ShanaLMoore** [comment]
I am able to create a work off of main so I'm going to close this ticket. 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/dd3d3490-c829-4317-8c68-f10f1836cccc)
