### ISSUE TITLE
Missing 'Collections section' on home page

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#593]
## Summary
The original site has an `Explore Collections`, along with a button that leads to all collections. The knapsack version does not have either. See screenshot below for how it should look:

![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/8c127d4a-dc0e-4843-9d39-3da7e6db5c2c)

## Accepted Criteria
- [ ] The home page layout looks as expected:
    - [ ] for 'adl' tenant, it has an `explore collections` section along with a link that takes the user to `all collections`
    - [ ] The non-functional twitter feed is removed
    - [ ] The homepage respects font selection in the admin appearance tab
    - [ ] The featured works show as orderable for those with ability to order them, and otherwise display in tiles.
    
 ### To Test:
 View the homepage while logged in with admin rights:

- [ ]  - featured works will appear as a draggable list
- [ ]  - page will be formatted correctly

 Log out

- [ ] - featured works will display as tiles. 
- [ ] - The rest of the page will not change

**Comment by laritakr** [comment]
Only the `adl` tenant shows X (formerly known as Twitter) and collections. These appear on the adl tenant. Further work may be needed to finetune the home page layout.

**Comment by laritakr** [comment]
@KatharineV There ARE ways to highlight and change collections, but your home page layout has them hardcoded... I remember doing the work to manually change them a while back. 

I'm not sure what it would take to use the same layout but use what is specified within the tenant, but I will look at that as I continue the work to fix the homepage layout to get a better idea.

**Comment by KatharineV** [comment]
@laritakr If the latest version of Hyku does include the option to feature collections through the UI, then I'd like to know more, so thanks for looking into it. When we worked with Summer on the current customized homepage, she came up with the hardcoded "featured collections" for us as a temporary workaround until we could upgrade to a version that allowed us to highlight collections and change them at will (just like featured works?). That was my understanding at the time. I could have been wrong!

**Comment by laritakr** [comment]
There is definitely a way to feature collections like you feature works, but it looks like lot of your UI is overriding that. I don't see option on the collections themselves either. I'm not sure how it all works, but I'm looking into it, and it is something we can plan for future work.

**Comment by laritakr** [comment]
Making collection featuring automatic will require an unknown but significant amount of work, as there are numerous customizations to the layout. At this point, this work is beyond the scope of this task, but it can be looked into with a future ticket.

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!

View the homepage while logged in with admin rights:

 - [x] featured works will appear as a draggable list
 - [x] page will be formatted correctly
 
<details><summary>Screenshots</summary>
![image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/2d0f9316-008d-4bcd-b94f-97640b67f694)

</details>

 - [x] featured works will display as tiles.
 - [x] The rest of the page will not change

<details><summary>Screenshots</summary>
![image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/5c0e4b02-b7e4-4e51-a488-4477d85137ad)

</details>

**Comment by KatharineV** [comment]
Team, I'm trying to do client QA but I don't see what passed your QA. Can you confirm which knapsack tenant I should be testing on? And can you share the screenshots from Jill's comment above again? They're not loading for me. I just see this: 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/679fe162-5951-482a-b9ef-7addbd317861)

**Comment by KatharineV** [comment]
Team, I'm trying to do client QA for this ticket, and here's what I can confirm. There are two major issues I see: 1. The "Explore Collections" feature with hardwired links to collections is missing from the homepage, and 2. The repository is missing the Helvetica Neue font, which is the one used by our sites. 

Accepted Criteria

    The home page layout looks as expected:
        for 'adl' tenant, it has an explore collections section along with a link that takes the user to all collections NO - FEATURE IS MISSING
        The non-functional twitter feed is removed YES - FEATURE IS REMOVED
        The homepage respects font selection in the admin appearance tab YES AND NO - FEATURE WORKS BUT IS MISSING FONT HELVETICA NEUE, WHICH IS USED ON ADVENTIST SITES
        The featured works show as orderable for those with ability to order them, and otherwise display in tiles. YES

To Test:

View the homepage while logged in with admin rights:

    - featured works will appear as a draggable list YES
    - page will be formatted correctly NO - COLLECTIONS ARE MISSING AND CORRECT FONT OPTION IS MISSING

Log out

    - featured works will display as tiles. YES
    - The rest of the page will not change YES

**Comment by laritakr** [comment]
@KatharineV only the adl tenant has the explore collections section. When I go to https://adl.adventist-knapsack-staging.notch8.cloud/?locale=en I see the collections.

However, I'm positive that I was told a different font to use, so you are likely right that the font you are asking about is not there. That will require additional changes to make sure it gets included. Is there a different ticket related to font, since this one is related to the collections?

**Comment by KatharineV** [comment]
@laritakr Thanks for reminding me of the adl-specific tenant on Knapsack. My testing has been focused on the "testing" environment and I literally forgot to check the adl tenant. You're right and it's displaying the hardwired collections as expected, so I'll shift this ticket to the next column. There isn't a separate ticket for font yet, so I will create one.
