### ISSUE TITLE
OCR issues

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#609]
# Summary
OCR search is not highlighting as expected

# Acceptance Criteria
When searching for OCR, if there's a match it should: 

- [ ] be highlighted in the catalog search results as a "snippet"
- [ ] auto fill the Universal Viewer and highlight the matches, by clicking into the work from the catalog search results
- [ ] A user should also be able to manually type a search into the UV and get highlighted matches

# Testing Instructions
From the [catalog search page](https://demo.adventist-knapsack-staging.notch8.cloud/catalog?locale=en) search for the word 'lamp'
You should find a match, and the word 'lamp' will be highlighted in the search results
click into the work
the word lamp should auto search the universal viewer and highlight a match
manually try typing other words. If there's a match, it should be found and highlighted. If there's not, it won't. 

# STAGING EXAMPLE 

Searched for "stare" then clicked into the work

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/1bece75d-1a17-438c-bd70-4f5629fe664c)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/a9bc4d2a-fd2d-47b3-ad2e-304500fa71f3)

# KNAPSACK

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/7750f7a5-e3c4-4898-9890-faa0cf54f8bc)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/5011dc7e-0619-4f52-b644-0b7e67ad9ced)

Manually typing "stare" in the UV: 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/53baa02d-1f84-4d09-92f5-978a694a2906)

**Comment by jillpe** [comment]
SoftServ QA:

When searching for OCR, if there's a match it should:

- [ ] be highlighted in the catalog search results as a "snippet"
- [ ] auto fill the Universal Viewer and highlight the matches, by clicking into the work from the catalog search results
- [ ] A user should also be able to manually type a search into the UV and get highlighted matches

**Comment by ShanaLMoore** [comment]
I naturally started to QA this while assisting Jill with testing instructions. ❌ 

Sending this back for work. In staging clicking into the work does not auto search the UV

Demo: https://share.zight.com/v1un4geg

**Comment by ShanaLMoore** [comment]
This appears to suddenly be working again on staging 🤔 demo: 


https://github.com/scientist-softserv/adventist-dl/assets/10081604/b7d91b59-5936-49e8-8d97-54d7246e65d5

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass

- [x] be highlighted in the catalog search results as a "snippet"
- [x] auto fill the Universal Viewer and highlight the matches, by clicking into the work from the catalog search results
- [x] A user should also be able to manually type a search into the UV and get highlighted matches

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/63a31a5f-83a1-4473-ad6e-0f4e3746245c)



https://github.com/scientist-softserv/adventist-dl/assets/84697174/315a1334-23cc-42e1-ba66-f48713ffd001



![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/e87250db-28ff-4fc0-877b-9229a928503f)


</details>
