### ISSUE TITLE
CatalogSearch feature parity

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#611]
# Summary 

In adventist proper's staging, work details are displayed in the catalog search results page. 

For example, for Journal article we see the following displayed: 
- Author
- Part of
- Date
- Subject
- Source
- Description

This ticket is to check each work type and/or make adventist knapsack display the same. Notice we also have a lot of translations missing.

## Staging example
![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/399c0dd8-1453-4984-8865-af39554072f3)

## ADV Knapsack example

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/691387be-115c-4d7c-937e-c2b2b6cac0e2)

**Comment by jeremyf** [comment]
The fonts are different but the translations are up (I think someone's working on the UI tests for fonts)

**Comment by KatharineV** [comment]
Testing results

Journal Article

- On prod: Author, Part of, Date, Subject, Source, Description.
- On Knapsack: Author, Part of, Subject, Source, Description.
- Date field needs to be added. 

Image

- On prod: Author, Part of, Date, Subject, Source, Description
- On Knapsack: Author, Part of, Subject, Source, Description
- Date field needs to be added.

Published Work

- On prod: Author, Date, Subject, Source, Description.
- On Knapsack: Author, Date, Subject, Source.
- Need to add Description.

Generic Work
NOTE: This is called "Work" on ADL prod and "Generic Work" on Knapsack. 

- On prod: Author, Part of, Date, Subject, Source, Description.
- On Knapsack: Author, Part of, Date, Subject, Source, Description.
- Nothing to add.

Collection

- On prod: Author, Date, Subject, Description.
- On Knapsack: Author, Date, Subject, Description.
- Nothing to add.

Thesis
- On prod: Author, Date, Subject, Source, Description.
- On Knapsack: Author, Date, Subject, Source. 
- Need to add Description.

Conference Item:
- On prod: Author, Part of, Subject.
- On Knapsack: Author, Part of, Subject.
- Nothing to add.

Dataset
- On prod: Author, Date, Subject, Source.
- On Knapsack: Author, Date, Subject, Source.
- Nothing to add.

Exam Paper:
- On prod: Author, Subject, Source, Description.
- On Knapsack: Author, Date, Subject, Source.
- Nothing to add.
