### ISSUE TITLE
Content block text doesn't respect site font selection

### ISSUE THREAD

**Issue by laritakr** [scientist-softserv/adventist-dl#614]
<details>
<summary>Screenshots</summary>

![Image](https://github.com/scientist-softserv/adventist-dl/assets/17851674/54a67a7e-0835-44b4-bbb3-103b3b34ffaa)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/17851674/4e3a5ec5-8803-4246-917a-641bbe073419)

</details>

**Comment by ShanaLMoore** [comment]
It appears to be working to me. Did I miss something @laritakr ?

# STAGING



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/3b7f94b0-c4b8-4b63-846b-8688bacb4b29)




![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/1291ac81-4e8b-48e9-aa67-15cb1464c174)


## DEFAULT RESTORED (Nobile, sans-serif)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/0f366b70-8cd7-4959-b8b9-7c6bba61fca9)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/3d03fd86-b0a1-4bd7-95a3-0fb7a3366dd2)
