### ISSUE TITLE
Make "Official URL" field a clickable link

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#615]
Collection pages on our instance of Hyku have a field called "official URL," and we'd like the contents of that field to be a clickable link. Here is an example on ADL prod where the field is filled but the link is only text. 
https://adl.b2.adventistdigitallibrary.org/collections/711704be-8da7-48e1-b2fb-34057a838779?locale=en

**Comment by jeremyf** [comment]
Note: This is a problem in the existing application and likely one in the Knapsack.  What appears to be missing is a Blacklight rendering hook for URLs.  There's precedence for how we do this in other applications; looking now.

**Comment by jeremyf** [comment]
This is handled in https://github.com/samvera/hyrax/blob/b334e186e77691d7da8ed59ff27f091be1c2a700/app/presenters/hyrax/presenter_renderer.rb#L39-L45

We'll likely want to consider adding a `records/show_fields/_official_url.html.erb` file in the knapsack.

**Comment by jillpe** [comment]
SoftServ QA: ✅ Pass!



https://github.com/scientist-softserv/adventist-dl/assets/84697174/a53d3d04-d569-48ad-9e0b-cba60127b645

**Comment by KatharineV** [comment]
Team, this is working when I test it on Knapsack. https://demo.adventist-knapsack-staging.notch8.cloud/collections/66de37df-a236-4a1f-a48b-8dbe145e7c46?locale=en
