### ISSUE TITLE
Global Index / Institution list page not showing tenants (Knapsack)

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#616]
I do not see a list of each institution on the global index/institution list page https://adventist-knapsack-staging.notch8.cloud/ 
There are three tenants in this instance, but only the Hyku descriptive text is visible on the global page.
The three tenants are currently private, but I temporarily marked SDAPI as public, visited the global index page, and still didn't see the tenant listed there. The same Hyku descriptive text was all I saw.

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/2bf4fdb5-0c1b-4241-b2d6-b2b1917dcfcd)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/22d7d86f-d8d1-4235-a7ad-09d91de34736)

**Comment by laritakr** [comment]
@KatharineV can you show a screenshot of where this appears on your current version of the repo? I don't understand what you are trying to accomplish. Both production and the current knapsack staging look the same from what I can see.

**Comment by KatharineV** [comment]
@laritakr you are right, prod and knapsack look the same for me too. You can clarify expected behavior for me, and perhaps you'll determine that this ticket should close. I was following the Hyku Test Plan, which includes this screenshot of the landing page with icons for each tenant:

**Comment by laritakr** [comment]
That must have been made using another client's screenshots! They have a custom homepage that adds them.  

You have a lot of custom code as well, but the homepage you see on your site is the default.
