### ISSUE TITLE
Remember me box for user log in not working (Knapsack)

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#617]
When I check the remember me box on the user log in page, my username is NOT saved on the form the next time I log in. I can still use my browser settings to remember me, but the box in Hyku does not appear to do anything and doesn't "remember" anything. 

This is for Knapsack testing. I can't add labels at the moment.

**Comment by jeremyf** [comment]
As a note: A "Remember Me" will not populate the username field in the form, but instead is related to how we manage the session for the user.

**Comment by KatharineV** [comment]
@jeremyf that makes perfect sense. The Hyku Test Plan document should be updated to reflect that. It currently reads:
- I can check/uncheck a Remember me box
- When this box is checked, my username will be saved on the form the next time I log in

**Comment by jillpe** [comment]
closed this is a bug in hyku
