### ISSUE TITLE
Collection Show Page missing metadata fields (Knapsack)

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#620]
## Summary
I added metadata to every field on this sample collection, and I see several bugs with metadata. Some fields are not displaying at all, display incorrectly, or lose content with edit/save.

https://demo.adventist-knapsack-staging.notch8.cloud/dashboard/collections/84931366-bcc6-406c-9609-06dee6fc1318?locale=en

Fields displaying INCORRECTLY on public view: 
License field shows a URL rather than text. The URL is not clickable.

Fields that are MISSING on the public view, despite containing data on the edit page:
Abstract, Publication Geocode, Alternate title, Location, All versions of the date field, Dept school or faculty, DOI, former identifier, Funder, Identifier, Issue, managing organization, note, official URL, pages, part of, place of publication, publication status, output, latitude, longitude, location.

Fields that are MISSING and they clear on EDIT/SAVE:
date created, publication status

## Testing Instructions
- [ ] License field show text
- [ ] Related URL is clickable
- The following display on public view
  - [ ] Abstract is present
  - [ ] Publication Geocode is present
  - [ ] Alternate Title is present
  - [ ] Location is present 
  - [ ] Date fields are present
  - [ ] Dept school or faculty is present
  - [ ] DOI is present
  - [ ] Former Identifier is present
  - [ ] Funder is present
  - [ ] Identifier is present
  - [ ] Issue is present
  - [ ] Managing Organization  is present
  - [ ] Note is present
  - [ ] Official URL is present
  - [ ] Pages is present
  - [ ] Part of is present
  - [ ] Place of Publication is present
  - [ ] Publication status is present
  - [ ] Output is present
  - [ ] Latitude is present
  - [ ] Longitude is present
  - [ ] Location is present

- The following display on the edit/save
- [ ] Date created
- [ ] Publication status

**Comment by jeremyf** [comment]
Fields missing from public views was addressed with https://github.com/scientist-softserv/adventist_knapsack/pull/71

**Comment by jillpe** [comment]
SoftServ QA: 
- [ ] License field show text
- [ ] Related URL is clickable
- The following display on public view
  - [ ] Abstract is present
  - [ ] Publication Geocode is present
  - [ ] Alternate Title is present
  - [ ] Location is present 
  - [ ] Date fields are present
  - [ ] Dept school or faculty is present
  - [ ] DOI is present
  - [ ] Former Identifier is present
  - [ ] Funder is present
  - [ ] Identifier is present
  - [ ] Issue is present
  - [ ] Managing Organization  is present
  - [ ] Note is present
  - [ ] Official URL is present
  - [ ] Pages is present
  - [ ] Part of is present
  - [ ] Place of Publication is present
  - [ ] Publication status is present
  - [ ] Output is present
  - [ ] Latitude is present
  - [ ] Longitude is present
  - [ ] Location is present

- The following display after an edit/save
- [ ] Date created
- [ ] Publication status

<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/3feafd90-da69-44ae-a96a-7370165dc0e8)


</details>

**Comment by jeremyf** [comment]
The Collection does not have an alternative title, so I'm considering that out of scope.  I do have an "Identifier" fix incoming.

**Comment by KatharineV** [comment]
@jeremyf I see a field called "alternate title" on the edit page of a collection. That was the field I meant to reference. Here's what it looks like on the backend. 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/603e737c-284b-4493-a566-b3cf48a4889c)

**Comment by KatharineV** [comment]
Team, I'm testing a collection on Knapsack today, and many fields are completely missing from the edit page now. I'm not sure how to proceed. This ticket dealt with fields that showed on edit but didn't show on save/public view. That was fixed for 99% of the fields...but now the fields have disappeared completely. This seems like a new problem, and it's a pretty dramatic change. I'll mention it here, in case it's related to this ticket. I'll comment here and reference the new ticket once I make it.

**Comment by KatharineV** [comment]
Every field works as expected today, except for Publication Status. That field still clears whatever I enter on the back end when I edit and save. The metadata doesn't save and doesn't appear on the user view. 

Collection used for testing: https://demo.adventist-knapsack-staging.notch8.cloud/collections/2c0f7ee5-e501-4700-b947-a524467b2fa6 

https://demo.adventist-knapsack-staging.notch8.cloud/dashboard/collections/2c0f7ee5-e501-4700-b947-a524467b2fa6/

**Comment by KatharineV** [comment]
ADL QA: All fields display as expected, including after edit and save.
