### ISSUE TITLE
Can't search for a work from the dashboard

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#623]
On demo.adventist-knapsack, I visited the works page of the dashboard. I was logged in as Admin@example.com. I searched for an image that I deposited in the repo via the UI. The title of the work is "[baby bunny](https://demo.adventist-knapsack-staging.notch8.cloud/concern/images/baby_bunny_baby_bunny?locale=en)." Searching the work "bunny" in my works and in all works resulted in an error message:

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/6ba87874-f499-4752-b8af-6f80c3d15241)

However, the work is listed in the dashboard. I just can't search for it. See below for screenshot of the work in the dashboard view. 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/644449a0-6a4c-4d7b-a103-dc8c8394257a)

**Comment by KatharineV** [comment]
The failed search behavior is also present when I try to search for a collection through the dashboard.

**Comment by jeremyf** [comment]
Likely related to #622

**Comment by jillpe** [comment]
SoftServ QA: ✅  Pass!

- [x] Search Catalog
<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/bd308807-bcfe-4c48-a5d8-a6a18b2eed4b)


</details>

- [x] Dashboard Search
<details><summary>Screenshots</summary>


![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/919f7eae-8cca-45e9-9284-a12a75bfc1d5)


</details>

**Comment by KatharineV** [comment]
This is not working when I search for a work or collection from the dashboard unless I search more than one word. This isn't good, because we may have collections with names that are just one word, and we certainly have words with one word titles.

Search for a collection with one word = no results.

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/3c7eda68-5ae2-440f-98b3-0a322b7fbffa)

Search for a collection with two words = correct results.


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/ec45ab49-b302-4c84-a9c8-f70bc9968c57)


Search for a Work with one word = no results.


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/2ea77e87-9889-4422-94ee-871f2852fc67)

Search for a Work with two words = correct results. 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/d6401517-c9bd-4b3c-80a8-6e112e23c95f)


Example of a one-word collection title on ADL prod: https://adl.b2.adventistdigitallibrary.org/collections/711704be-8da7-48e1-b2fb-34057a838779?locale=en 

Example of a one-word work title on ADL prod: https://adl.b2.adventistdigitallibrary.org/concern/published_works/22250261_cardinal

These examples are proof of the concept that we do have single-word titles and need to be able to find them via the dashboard. This is especially important for collections, because we can't access the edit button from the live user view. We have to find the collection in the dashboard.

**Comment by KatharineV** [comment]
@ShanaLMoore in the post-Knapsack deployed environment, I can no longer search for collection titles using just one word. We need to be able to search and find using one word, because we have collection titles that are only one word long (example: [Spectrum](https://adl.b2.adventistdigitallibrary.org/collections/711704be-8da7-48e1-b2fb-34057a838779)). I've flagged you because I'm not sure...should I create a new ticket? Or reopen this one? The problem seems similar to one that was fixed in the Knapsack demo with this ticket.

**Comment by ShanaLMoore** [comment]
@KatharineV we already have a ticket for this. 😓 ref: https://github.com/scientist-softserv/adventist-dl/issues/622

**Comment by ShanaLMoore** [comment]
However I should add that, according to @laritakr and even better solution has been contributed back to hyku from pals. When we upgrade you again, you should receive it. 

However in the meantime, tagging me on this is helpful to know we've seen and have fixed similar behavior before.
