### ISSUE TITLE
Author field should not be required

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#627]
In demo.adventist-knapsack, I see that the Author field is required for some work types. We do not have this field required on production. We would like Knapsack to match and only require the Title and Rights statement. 

Work types affected:

- Conference Item
- Dataset
- Exam Paper
- Journal Article
- Published Work
- Thesis

Work types NOT affected: 

- Generic Work
- Image

Screenshot of example (Conference Item)

KNAPSACK

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/37206b7a-55af-43d5-a99b-2ba8f0994bce)

PRODUCTION

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/e8051075-641f-40a7-ab91-57ec42dfbf19)

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 

- [x] author is not a required field for conference item in knapsack [staging](https://demo.adventist-knapsack-staging.notch8.cloud/concern/conference_items/new?locale=en)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/ab67f84f-b838-4c2e-9327-5bd14dcbff6a)

**Comment by KatharineV** [comment]
ADL QA: Checked a few new works on adl knapsack staging and author/creator was not a required field.
