### ISSUE TITLE
Metadata fields not showing on Work public view

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#629]
Some metadata fields can have content entered on the edit screen, but when I save, the content is not present on the user view. The fields don't show up at all. Some of these are new metadata fields in Knapsack that I can't test against our existing Hyku. Some of the fields are in the older version and I can confirm that they show on ADL prod but not in Knapsack.

New Fields:

- Access Rights
- Rights Notes

Screenshot of edit screen[ of this work.](https://demo.adventist-knapsack-staging.notch8.cloud/concern/theses/van_poster_final_thesis?locale=en) 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/fe271b11-9538-4d07-9987-a9f4ff8295f5)

Existing fields:

- License (see it displaying on prod [here](https://adl.b2.adventistdigitallibrary.org/concern/generic_works/wdf_0022_002_special_testimonies_no_4_for_ministers_and_workers?locale=en))
- Publication status (on prod [here](https://adl.b2.adventistdigitallibrary.org/concern/journal_articles/test_123_bees_test_of_journal_article_work_types_fields?locale=en))

Work types affected:

- Published Work (license)
- Conference Item (all fields)
- Journal Article (license, publication status)
- Exam Paper (Access rights, rights notes, license)
- Dataset (Access rights, rights notes, license)
- Thesis (Access rights, rights notes, license)
- Images (Access rights, rights notes, license--can't even enter data into these fields because trying to save generates "We're sorry, but something went wrong" message)
- Generic Work (Access rights, rights notes, license--can't enter data right now because of "We're sorry, but something went wrong" error message)

# Testing Instructions
Create a work of each work type, filling in each term.
Ensure that each term appears on the show view for the work. 

<details>
<summary>Terms by work type</summary>

The expected terms for each type of work are listed below, along with their sequences on the form and show pages.

![adv metadata by work type ](https://github.com/scientist-softserv/adventist-dl/assets/17851674/a349364a-71fa-4f9a-bae4-e98b911c8bc7)
</details>

<details>
<summary>Screenshots showing new terms</summary>

![Screenshot 2023-10-16 at 7 50 59 PM](https://github.com/scientist-softserv/adventist-dl/assets/17851674/d4594a35-f503-4394-a083-18c2b18e1c7a)

![Screenshot 2023-10-16 at 8 08 34 PM](https://github.com/scientist-softserv/adventist-dl/assets/17851674/dda51499-9fdd-4ca
9-87ad-7943d1250dab)

</details>

**Comment by laritakr** [comment]
You are referring to some existing terms that your current app has specifically from being shown on the works:
`Conference Items`, `Datasets`, `Journal Articles`, `Published Works` and `Theses` exclude `description` and `license` (they show `abstract`)
`Exam Papers` exclude `license`
`Generic Works` and `Images` should show all terms
`Rights Notes` and `Access Rights` are new terms for all work types, but they were for some reason excluded from `Journal Articles`. They can either be excluded from other work types, or made to appear on the show view - do you have a preference?

**Comment by KatharineV** [comment]
@laritakr I may not be understanding correctly, so please bear with me. I didn’t know that my predecessor had the team suppress any fields from any work types. There is no reason I can think of for why we would suppress any fields. So, I would ask for all new fields to appear in our version of Hyku on every work type where they are intended to appear. This applies to Rights Notes and Access Rights, I understand. 

As for the other fields, forget I mentioned them I guess. My predecessor kept literally no documentation of decisions he made like fields to suppress, so I had no way of knowing what to look for. My apologies for wasting your time. It is very difficult to do this testing in the dark. I am doing my best.

**Comment by laritakr** [comment]
No worries, Katharine... this is confusing for both of us! 

I am doing some verification and we're trying to do some cleanup in the code to make this more straightforward for the future. I put together a spreadsheet where I am verifying the metadata, so I may have more questions next week. I appreciate your patience as I try to figure it out. :) But unless you have a reason to suppress any fields from showing, I intend to have them show.

**Comment by laritakr** [comment]
I will add that publication status is DEFINITELY a bug... it is not persisting on the work so it does not display. I will continue working to get this resolved.

**Comment by KatharineV** [comment]
Thanks, LaRita. I agree that there's no reason to suppress any fields. If we don't enter metadata on the backend, they don't show on the front, so that's a fine solution. I can't think of any reason to redact a field from the backend, thereby making it inaccessible for future use, as if I know all the possible future use cases for our instance of Hyku. I don't have that much hubris. So, yes, please do make anything show that is available, and I'll plan for a future maintenance ticket to release the fields that were suppressed in earlier rounds of work under a different mindset.

Thank you also for catching publication status. That one is weird!
________________________________

**Comment by kirkkwang** [comment]
# QA Results
- [Conference Item](https://adl.adventist-knapsack-staging.notch8.cloud/concern/conference_items/aark_a_test_conference_item?locale=en) ✅
- [Dataset](https://adl.adventist-knapsack-staging.notch8.cloud/concern/datasets/aark_dataset_a_test_dataset?locale=en) ✅
- [Exam Paper](https://adl.adventist-knapsack-staging.notch8.cloud/concern/exam_papers/vero_a_test_exam_paper?locale=en)✅
- [Journal Article](https://adl.adventist-knapsack-staging.notch8.cloud/concern/journal_articles/human_usability_producer_a_test_journal_article?locale=en) ✅
- [Published Work](https://adl.adventist-knapsack-staging.notch8.cloud/concern/published_works/eum_autem_totam_a_test_published_work?locale=en) ✅
- Thesis 
- Generic Work
- Image

# Notes

I couldn't test the Location probably because GeoName isn't set up on staging.

I'm noticing an in consistency with the date fields
<img width="393" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/55897bc1-d8f6-49bd-a57e-89b202ded739">

Sometimes it's doing MM/DD/YYYY and sometimes DD/MM/YYYY, first one should be November 1st and second one is November 9th.

**Comment by kirkkwang** [comment]
with regards to the date appearing weird, this [PR](https://github.com/scientist-softserv/adventist_knapsack/pull/101) seems to address it

**Comment by KatharineV** [comment]
Fields are showing as expected on Knapsack Demo. I created all new works of every type today, and I filled in every field. With the exception of those that were intentionally suppressed in the past, all fields show on the user side now.
