### ISSUE TITLE
Hidden catalogue search bar

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#631]
## Summary 
The catalog search page looks a little funky. The search bar is hidden behind the nav bar when the screen size is between 768 & 948

![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/42b20a2f-e6ab-4633-ba30-220771e693a8)

## Acceptance Criteria
- [ ] the catalog search bar is present at any screen width on the catalog search page

**Comment by jillpe** [comment]
This also appears to be happening on the work show page and collections show page

**Comment by ShanaLMoore** [comment]
Locally this isn't an issue: 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/229ebecb-4dfc-4d0c-8005-ad3ce6999ad3)



On staging it is. 🤔 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/65d195f6-8160-4048-8c3a-9f42a6a12509)

**Comment by ShanaLMoore** [comment]
This issue isn't seen locally. Additionally, for staging, when I use chrome with these dimensions the issue isn't present. However it is present in firefox 🤔 

## Local


![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/cdb3cc5e-17ce-45b3-9236-686ee7b374c7)



# Staging (Chrome) 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/faa60d9e-796d-48fe-95e7-971d8e195547)


# Staging (Firefox)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/3f06e001-f8ff-49a3-b89e-04d033fd22bf)

**Comment by ShanaLMoore** [comment]
When compared to the functionality of adv production, the issue is that the hamburger isn't collapsing the nav options in knapsack: 



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/e4036811-71f2-4e27-ae85-4ec2aacde567)

**Comment by ShanaLMoore** [comment]
# QA RESULTS: Pass ✅ 

Thanks for the help here @kirkkwang !

- [x] the breakpoints/responsiveness have been corrected. the hamburger menu displays in lieu of the nav bar on smaller screens, and no longer blocks the search bar. 


![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/f52db6e7-0fdb-433d-b80e-0cd8fda81231)
