### ISSUE TITLE
Image and Generic creation fails

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#632]
## Summary
When trying to create a generic and image work type, pressing the save button results in an error:

![Image](https://github.com/scientist-softserv/adventist-dl/assets/84697174/a493c80f-f0ee-4825-a130-9bc711bf2764)

## Accepted Criteria
- [ ] As a user, I can create a generic and image work type and it saves

**Comment by laritakr** [comment]
I suspect this is due to @jeremys change via pull request https://github.com/scientist-softserv/adventist_knapsack/pull/77

**Comment by laritakr** [comment]
The definitions of date_created do not agree between models.

![Screenshot 2023-10-11 at 7 01 07 PM](https://github.com/scientist-softserv/adventist-dl/assets/17851674/aae6a1f6-52c2-4fff-b340-2a260df420fc)

**Comment by laritakr** [comment]
I was able to create both types of works in staging, with no errors. 
https://demo.adventist-knapsack-staging.notch8.cloud/concern/generic_works/ut_autem_quia_molest_generic_work_deserunt_dolore_reru?locale=en
https://demo.adventist-knapsack-staging.notch8.cloud/concern/images/totam_aut_eum_quos_a_image_pariatur_alias_cons?locale=en

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 

I am able to manually create [GenericWork](https://demo.adventist-knapsack-staging.notch8.cloud/concern/generic_works/ada65cd4-82d5-46fe-94dd-8b1921cc34b8?locale=en) and [Images](https://demo.adventist-knapsack-staging.notch8.cloud/concern/images/613665fa-e302-4ef8-8341-4d0a0e296648?locale=en)

demo: https://share.zight.com/lluOokkv
