### ISSUE TITLE
500 errors in Staging

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/adventist-dl#641]
# Summary

During QA I noticed that clicking on pre-existing works in staging leads to 500 errors

ref: https://demo.adventist-knapsack-staging.notch8.cloud/catalog?locale=en&page=4&q=pdf&search_field=all_fields

DEMO: https://share.zight.com/6quwN1dj

## Notes

Server Logs: 
[adventist-knapsack-staging-hyrax-6c4fcb77d6-6wwn2_hyrax(1).log](https://github.com/scientist-softserv/adventist-dl/files/13245350/adventist-knapsack-staging-hyrax-6c4fcb77d6-6wwn2_hyrax.1.log)

**Comment by kirkkwang** [comment]
I was able to replicate the error, `invalid date` matches the error from the logs
![image](https://github.com/scientist-softserv/adventist-dl/assets/19597776/28a81c43-f5c9-4450-b55c-cdf12579621d)

**Comment by ShanaLMoore** [comment]
# QA RESULTS: PASS ✅ 

Clicking on pre-existing works no longer causes 500 errors: 

DEMO: https://share.zight.com/v1uB00nW
