### ISSUE TITLE
Journal article custom field name not present on Knapsack

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#658]
In Adventist's version of Hyku, the Part Of field in the Journal Article work type shows with the label "Periodical." In Knapsack, that field still shows as "Part of." For consistency, we'd like this field updated to match the customized label.

See this work for example of field label "Part of": https://demo.adventist-knapsack-staging.notch8.cloud/concern/journal_articles/pur_2010_feb_pacific_union_recorder_february_2010?locale=en 

See this work for example of field label "Periodical": https://sdapi.s2.adventistdigitallibrary.org/concern/journal_articles/pur_2010_feb_pacific_union_recorder_february_2010?locale=en 

Same metadata for both examples above. Only the environment is different.

## Acceptance Criteria
- [ ] The label Part Of should display as Part Of for all models except for Journal Articles
- [ ] For Journal Articles, Part Of should display as Periodical instead

## Testing Instructions
Either find or create a Generic Work. If new, be sure to fill in all required fields (and aark_id). Also fill in a value for "Part Of" and save. Visit the work's show page. The display of this value should have a label that says "Part Of". 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/b5645159-5c09-4b19-a781-2ff1ac344cd6)

Either find or create a Journal Article. If new, be sure to fill in all required fields. Also fill in a value for the "Periodical" field and save. Visit the work's show page. The display of this value should have a label that says "Periodical". 

![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/4f492c35-b438-4867-87be-17c33a40499f)

**Comment by ShanaLMoore** [comment]
This is interesting. 

In attempts to reproduce this locally I created an sdapi article importer, limit 10. Both are from commit 2b50ce5. 

## Staging: 
(says Periodical)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/ff6491cc-3de4-43d1-8e21-c68b3089c5d7)



![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/d2a651e6-f386-405d-9db7-f54e4c4dcbb5)



## Locally: 
(correctly says Part Of)




![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/7c757d1c-7443-43b5-b83b-d8c061b3c0d8)




![Image](https://github.com/scientist-softserv/adventist-dl/assets/10081604/15cf026a-c170-429d-988d-afddebf55a6d)

**Comment by ShanaLMoore** [comment]
# QA Results:

**Comment by KatharineV** [comment]
ADL QA: The label is updated on ADL knapsack staging. I created a new journal article and the field is correct. Thank you!
https://adl.adventist-knapsack-staging.notch8.cloud/concern/journal_articles/08657fa2-95e2-4a35-8d47-9922c7f75427?locale=en
