### ISSUE TITLE
Deploy knapsack to prod

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/adventist-dl#714]
likely includes copying files form existing prod to new prod and then updating the ingresses.

**Comment by jillpe** [comment]
Adventist needs a separate one for knapsack

**Comment by ShanaLMoore** [comment]
current set up for prod would over take the current prod instance. I don't think we want to do that. 

https://github.com/scientist-softserv/adventist_knapsack/blob/main/ops/production-deploy.tmpl.yaml#L43

**Comment by ShanaLMoore** [comment]
team prefers to wait until ingests completes on adventist, before switching them over to knapsack
