### ISSUE TITLE
Spike: Determine if adventist is ready to switch to knapsack

### ISSUE THREAD

**Issue by jillpe** [scientist-softserv/adventist-dl#741]
## Summary
Look at tickets that have been done since we last worked on the knapsacking and determine if they need to be addressed.

## Acceptance Criteria
- [ ] The above summary is addressed

**Comment by jillpe** [comment]
https://assaydepot.slack.com/archives/C0313NKG2DA/p1710775684524539?thread_ts=1710519636.234079&cid=C0313NKG2DA

**Comment by ShanaLMoore** [comment]
We need to see what has been added to adv since they were knapsack and determine if that code needs to go into their knapsack. 

Rob said he would take care of this since he and Kiah introduced and are most familiar with those changes.
