### ISSUE TITLE
Adventist Stats for Server Migration

### ISSUE THREAD

**Issue by DraxIndustries79** [scientist-softserv/adventist-dl#745]
We need to share some stats with Adventist's new cloud provider so they can look at what to provision.  Please pull our current stats on:
- [x] cpu
- [x] ram
- [x] disk space
- [x] bandwidth

April, Rob said you should be able to pull this and if not it would be a good pairing opportunity for you two.

**Comment by aprilrieger** [comment]
@DraxIndustries79 here is the google doc you can share with the client with the stats in question and a handy shopping list for the client: https://docs.google.com/document/d/11ztp_DkeZSBQboYPZ12JDOmvjd9oXgsJXPTY2tMUvHs/edit?usp=sharing

**Comment by aprilrieger** [comment]
https://docs.google.com/document/d/11ztp_DkeZSBQboYPZ12JDOmvjd9oXgsJXPTY2tMUvHs/edit?usp=sharing
