### ISSUE TITLE
Action buttons missing from works when logged in

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#747]
After the Knapsack upgrade, action buttons are missing from works on production. The buttons we expect to see are Edit, Delete, Attach Child, Add to Collection, and Feature. See screenshots below for an example of ADL staging (with buttons) compared to ADL and SDAPI prod (no buttons). 

Staging with buttons: 

https://adl.s2.adventistdigitallibrary.org/concern/images/p005873_clinton_theological_seminary_sextelles_1921?locale=en
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/d7506b95-305e-4d14-92ae-f435698d966f)

Prod without buttons: 

https://adl.b2.adventistdigitallibrary.org/concern/published_works/22266468_cardinal_1986
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/cbbbe983-dcb9-4a35-b7cc-c021ca1d72d0)

https://sdapi.b2.adventistdigitallibrary.org/concern/journal_articles/davarlogos_2023_2_59_93_the_compatibility_of_christ_s_ascension_in_the_epis?locale=en
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/2a044f27-dc93-46ef-9770-43bc66181365)

**Comment by KatharineV** [comment]
Confirmed that action items are showing on ADL and SDAPI production and staging when I am logged in. Screenshots below are just production. Note that we're seeing the "Public" tag, which wasn't present before. At some point that was masked in our instance of Hyku. Not sure when it came back, but it seems like Knapsack revealed it, since the pre-Knapsack staging screenshot at the top of the ticket doesn't include the Public visibility tag. 

Note also that the location and look of the action buttons has changed. That's inconsequential and I don't want the team to waste time moving the buttons, but I would like to see the Public visibility tag go away, at least for visitors who are not logged in. When viewing works while logged out, there's no point to the visibility tag. If you can see it, it's public, so the tag is clutter. Can it go away? Does this need its own ticket, or is it related to the other buttons at the top of a work? 


ADL
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/2b4b3087-e581-4c5d-ac9f-10d55e089b71)


SDAPI
![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/47fd5ba2-e54f-4994-8550-59da6c638a8c)

**Comment by ShanaLMoore** [comment]
@KatharineV I'm going to create a new ticket for the public tag issue. If you are ok with the buttons as they are, please consider re verifying. Otherwise we can also make a ticket to change their position.

**Comment by KatharineV** [comment]
Thanks, @ShanaLMoore . I'll move this ticket to done, since the buttons are present and they work. I really don't think the button location matters at all, as long as they're close to where people will look for them, and they work.
