### ISSUE TITLE
Can't add individual works through the UI post-Knapsack

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#756]
Yesterday (4/17) and today (4/18) I've tried and failed to add works to ADL prod through the UI, for the purposes of testing Knapsack and working through tickets. The system freezes and won't progress past the "Select type of work" dialogue box. See screenshot below, where you see the progress icon at the top of the browser tab, which is the only thing that moves after I select a work type and click "Create work." Everything else freezes and never works after that point. Eventually, we get a 504 Gateway time-out (second screenshot).

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/962efcf3-1132-4f70-847e-2973ec42013c)

![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/c841780c-bb30-42f7-9555-ab0a7b78c571)

**Comment by KatharineV** [comment]
Just confirmed that I can't add individual works through the UI on ADL staging either.



![Image](https://github.com/scientist-softserv/adventist-dl/assets/118196520/ff83950a-4d2f-4da0-b315-1aed2a1dedc0)

**Comment by KatharineV** [comment]
On ADL prod I just tried to deposit a new work through an existing collection, and the UI still didn't accept the "create work" action. It timed out and failed.

**Comment by aprilrieger** [comment]
PRODUCTION
✅ Add a new work to an existing collection
- Video walk-through of behavior: https://share.zight.com/RBuA6Zg2
- Collection: https://adl.b2.adventistdigitallibrary.org/dashboard/collections/584dd02b-853b-45de-97d0-93dd2e264d9a?locale=en
- Private generic_work: https://adl.b2.adventistdigitallibrary.org/concern/generic_works/64d1ac7f-67f0-4e3f-9714-ca401f4d1813?locale=en

**Comment by KatharineV** [comment]
Functionality is working as expected with my testing today!
