### ISSUE TITLE
Bulkrax importers stuck pending in prod post-Knapsack

### ISSUE THREAD

**Issue by KatharineV** [scientist-softserv/adventist-dl#757]
I can get Bulkrax importers to run on staging, but everything I've launched on a production tenant today is stuck pending. It's been a few hours, and nothing is moving. This may be related to #755 and the importers that won't update, but I'm making a separate ticket for now, just in case. 

See these examples on ADL and SDAPI:

https://sdapi.b2.adventistdigitallibrary.org/importers/439?locale=en
https://sdapi.b2.adventistdigitallibrary.org/importers/438?locale=en

https://adl.b2.adventistdigitallibrary.org/importers/311?locale=en

**Comment by ShanaLMoore** [comment]
I believe things are working but rather slowly. There are about 7 jobs that are taking FOREVER to finish. We have a thread count of 10 so that really means when we start a new import, only 3 threads becomes available giving the appearance of a slow or stuck ingest.
