### ISSUE TITLE
Revisit Parser Mappings with 2022-10-27 Information and Later

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#85]
With https://gitlab.com/notch8/adventist-dl/-/merge_requests/209 we have a set of updated parser mappings.  However in 2022-10-27 Slack conversations there were modifications that were mentioned.  This ticket is to address the next round of parser mapping changes.

- Canonical Document for Desired Mappings :: https://docs.google.com/spreadsheets/d/1GEsyaFNias1JmnAkRLZbMYsBIaV-1rxl/edit#gid=1638457955
- Slack Thread for clarification :: https://assaydepot.slack.com/archives/G0311DN2YCA/p1666889729245869
- Additional Questions regarding :: https://assaydepot.slack.com/archives/G0311DN2YCA/p1666893112910419
- Further information :: https://docs.google.com/document/d/1LmGsLw95CqBmRkRk5WJPYi2Y9KIZpktaO2ac3-1sl8o/edit; in that document we've went through and added 

_At present this is not actionable and will require additional work to make actionable._

**Comment by DiemBTran** [comment]
Linked Items:

Blocks:

- Run a re-import on staging

Relates to:

- Epic: CSV Importer that accepts DC
- CSV Importer that accepts DC
- [3]DC term metadata mapping
- OAI Import `physicalDescription` in `MODS` isn’t mapping to extent
- OAI dateIssued in MODS sometimes fails to map to [text string field].
- OAI relatedItem/titleInfo/title not mapping to partOf/Series in a Published Work
- Compound subjects should appear as a single unit
- OAI originInfo/edition not mapping to Edition in published works
- Abstract is not mapping to abstract for generic work and image
- Incorrect metadata somehow populates the “partOf” field in Hyku and containing collections are duplicated and populated wrong.

**Comment by DiemBTran** [comment]
Related MRs:

[Updated shared parser mappings](https://gitlab.com/notch8/adventist-dl/-/merge_requests/209)
!209

**Comment by jillpe** [comment]
Closed in sprint meeting 11/14 - no longer relevant
