### ISSUE TITLE
[5] Fix OAI ADL import

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#86]
The OAI ADL Import is envisioned as using the same mappings as the CSV Parser.  Given that it's easier to test using a CSV file, we want to first run tests against the mappings using the CSV Parser.

Once we have a clean run of the CSV Parser, then we can begin on this ticket.

The OAI end point is described in https://playbook-staging.notch8.com/en/samvera/oai-feeds

Tasks:

- [ ] Run the OAI ADL parser against the end-point
- [ ] Get the appropriate OAI End Point for testing the import

**Comment by DiemBTran** [comment]
Tasks:

- Run the OAI QDC parser against the end-point
- Get the appropriate OAI End Point for testing the import

**Comment by DiemBTran** [comment]
Linked items:

- [3]DC term metadata mapping
- Test each field using the QDC parser

**Comment by DiemBTran** [comment]
Related MRs:

[Enabling the CSV Parser](https://gitlab.com/notch8/adventist-dl/-/merge_requests/202)

**Comment by DeonFranklin** [comment]
OAI Import was successful on staging.



![Image](https://user-images.githubusercontent.com/95306716/205539541-4e836a4f-0869-4d37-9d03-baba07000232.png)
