### ISSUE TITLE
[3] Files associated with a work show up as a string (not human-readable) under Related URL

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#87]
# Update 2023-03-13

For https://adl.s2.adventistdigitallibrary.org/concern/published_works/20121631_a_sketch_of_the_christian_experience_and_views_of_ellen_g_white?locale=en, we have importer entry https://adl.s2.adventistdigitallibrary.org/importers/36/entries/186119?locale=en.

As of 2023-03-13 there are three file sets associated with the work.  One of those has a title that is "[/concern/parent/20121631_a_sketch_of_the_christian_experience_and_views_of_ellen_g_white/file_sets/51da8624-4cd5-4867-bfbc-833557d3d1a6](https://adl.s2.adventistdigitallibrary.org/concern/parent/20121631_a_sketch_of_the_christian_experience_and_views_of_ellen_g_white/file_sets/51da8624-4cd5-4867-bfbc-833557d3d1a6)"

That is an incorrect title; it is the path for the file set.

# Summary

Files associated with a work show up as a string (not human-readable) under Related URL. Actual URLs put in that field on the edit side won’t show up.  This was previously reported but also restated in [Metadata oddities](https://docs.google.com/document/d/1LmGsLw95CqBmRkRk5WJPYi2Y9KIZpktaO2ac3-1sl8o/edit).

One example is: https://adl.b2.adventistdigitallibrary.org/concern/images/20119288_bessie_waggoner?locale=en

## Testing Instructions

With #128 we have some oddities with this field:

1. When I imported via CSV a column that has `related_url`; I should fetch that file and attach it to the work.  This "related_url" will not show as part of the work's metadata.
2. When I edit the work, there is a field for `related_url`; when I add a URL to that field and save it, I see the `related_url` on the metadata show page.  (note: we will not be downloading that URL)

## Recommendation

Remove the “Related URLs” from rendering on the show page.  These are the files that are attached to the works. Keep “Remote URLs” and ensure that they render as links.

## Acceptance Criteria

- [x] For https://adl.b2.adventistdigitallibrary.org/concern/images/20119288_bessie_waggoner?locale=en we will no longer render "Related URLs" (note this is production data)
- [ ] For https://adl.b2.adventistdigitallibrary.org/concern/journal_articles/14790893_2021_ehudddle_redefines_adventist_evangelism_in_north_america_exa?locale=en we will continue to render "Remote URLs" with a link to http://www.andrews.edu/library/car/cardigital/Periodicals/Adventist_Journey/2021/2021_06.pdf#page=8

## Discussion

This task involves looking at our metadata mappings and making sense of both files to import and URLs to use as reference.

Related URLs are used to download the files, but may not be the correct value.

Below is the [bulkrax mapping segment:](https://github.com/scientist-softserv/adventist-dl/blob/96cbb01f1bd858ec0b472fb89ce033e180dba4b1/config/initializers/bulkrax.rb#L62-L63)

    'remote_files' => { from: ['related_url'], split: ';', parsed: true },
    'remote_url' => { from: ['official_url', 'remote_url'], split: ';' },

In the above, the Hyku `remote_files` property comes from the `related_url` property provided by Adventist via CSV and OAI ADL data sources.  The `remote_url` and `official_url` are included to highlight the potential confusion that we should avoid.

Below we have the [Bulkrax::FileFactory#parsed\_remote\_files](https://github.com/scientist-softserv/adventist-dl/blob/96cbb01f1bd858ec0b472fb89ce033e180dba4b1/app/models/concerns/bulkrax/file_factory.rb#L30-L49) logic that parses the `remote_files`:

    def parsed_remote_files
          return @parsed_remote_files if @parsed_remote_files.present?
    
          @parsed_remote_files = attributes[:remote_files] || []
          # OVERRIDE Bulkrax 1.0.2 to override default_thumbnail
          @parsed_remote_files << attributes[:thumbnail_url]
          @parsed_remote_files = @parsed_remote_files.map do |file_value|
    	if file_value.is_a?(Hash)
    	  file_value
    	elsif file_value.is_a?(String)
    	  name = Bulkrax::Importer.safe_uri_filename(file_value)
    	  { url: file_value, file_name: name }
    	else
    	  Rails.logger.error("skipped remote file #{file_value} because we do not recognize the type")
    	  nil
    	end
          end
          @parsed_remote_files.delete(nil)
          @parsed_remote_files
        end

In the [Hyrax::CreateWithRemoteFilesActor](https://github.com/scientist-softserv/adventist-dl/blob/96cbb01f1bd858ec0b472fb89ce033e180dba4b1/app/actors/hyrax/actors/create_with_remote_files_actor.rb#L14-L26) we have the logic that attaches the `remote_files`:

    # @param [Hyrax::Actors::Environment] env
          # @return [Boolean] true if create was successful
          def create(env)
    	remote_files = env.attributes.delete(:remote_files)
    	next_actor.create(env) && attach_files(env, remote_files)
          end
    
          # @param [Hyrax::Actors::Environment] env
          # @return [Boolean] true if update was successful
          def update(env)
    	remote_files = env.attributes.delete(:remote_files)
    	next_actor.update(env) && attach_files(env, remote_files)
          end

In the above we convert the given `remote_files` to FileSet objects.  Then, in our presentation we use those FileSets to create the `related_url` display property.  See [SolrDocument#thumbnail\_url](https://github.com/scientist-softserv/adventist-dl/blob/96cbb01f1bd858ec0b472fb89ce033e180dba4b1/app/models/solr_document.rb#L67-L71) below for those implementation details:

    def related_url
        file_set_ids.map do |fs_id|
          Hyrax::Engine.routes.url_helpers.download_path(fs_id)
        end
      end

Given that we are rendering the file sets as a list in the bottom portion of the show page, the `related_url` is unlikely to be what we intended.  It is likely that we want to use `remote_url` as provided above.

In the [./app/views/hyrax/base/\_attribute\_rows.html.erb](https://github.com/scientist-softserv/adventist-dl/blob/96cbb01f1bd858ec0b472fb89ce033e180dba4b1/app/views/hyrax/base/_attribute_rows.html.erb#L12-L20) we render both `resource_type` and `remote_url`.

    <%= presenter.attribute_to_html(:related_url, render_as: :external_link) %>
    <% if can? :read, :admin_dashboard %>
      <%= presenter.attribute_to_html(:resource_type, render_as: :faceted) %>
    <% end %>
    <%= presenter.attribute_to_html(:part_of) %>
    <%= presenter.attribute_to_html(:source, render_as: :faceted) %>
    <%= presenter.attribute_to_html(:place_of_publication) %>
    <%= presenter.attribute_to_html(:bibliographic_citation) %>
    <%= presenter.attribute_to_html(:remote_url) %>

In the case of `resource_type` we that as a root relative path (e.g. `/path/to/file/`) instead of an absolute url (e.g. `https://domain.org/path/to/file/`); which is why the we see text instead of a link (e.g. an A-tag).

In the case of the `remote_url`, we do not declare the link to `render_as: :external_link`, which means we would also have a plain text instead of a link.  *Note*, there are several different `_attribute_rows.html.erb` partials:

    ./app/views/hyrax/published_works/_attribute_rows.html.erb
    ./app/views/hyrax/conference_items/_attribute_rows.html.erb
    ./app/views/hyrax/theses/_attribute_rows.html.erb
    ./app/views/hyrax/datasets/_attribute_rows.html.erb
    ./app/views/hyrax/exam_papers/_attribute_rows.html.erb
    ./app/views/hyrax/journal_articles/_attribute_rows.html.erb
    ./app/views/hyrax/base/_attribute_rows.html.erb

And these require additional investigation, but the general principle remains the same.

**Comment by DiemBTran** [comment]
Linked items:

Blocks:

[Run a re-import on staging](https://gitlab.com/notch8/adventist-dl/-/issues/199)

**Comment by DiemBTran** [comment]
Jeremy - Oct 2022:

**Summary**

We need to revisit the source field name that has the URLs to the files we want to attach to the work.  Those attached files, in the Hyku instance, should likely not be rendered in as Related URL metadata for the work, as those files are listed below in the Relationship > Items section.

**Analysis**

There are two references for `related_url` that may be relevant:

-   In [Bulkrax v2.0.0 we have a mapping](https://github.com/samvera-labs/bulkrax/blob/f76b0bff90d3c704b0624a44e33bb4f2c7272273/lib/bulkrax.rb#L66) from `relation` to `related_url`.
-   In the [config/initializers/bulkrax.rb](https://gitlab.com/notch8/adventist-dl/blob/681a778bf68c21683a6cc474144048e0db70f5f9/config/initializers/bulkrax.rb#L62) of Adventist we have a mapping from `related_url` to `remote_files`.

In reading the code, the [SolrDocument#related\_url](https://gitlab.com/notch8/adventist-dl/blob/681a778bf68c21683a6cc474144048e0db70f5f9/app/models/solr_document.rb#L68-72) is to be the file sets associated with the work; however those are not rendering as URLs (but instead as paths).  See the code below:

```ruby
    def related_url
      self.file_set_ids.map do |fs_id|
        Hyrax::Engine.routes.url_helpers.download_path(fs_id)
      end
    end
```

During the ingest process, (e.g. [CreateWithRemoteFilesActor#create](https://gitlab.com/notch8/adventist-dl/blob/681a778bf68c21683a6cc474144048e0db70f5f9/app/actors/hyrax/actors/create_with_remote_files_actor.rb#L13-19)), we retrieve the `remote_files` and attach them as file\_sets to the work.

```ruby
    class CreateWithRemoteFilesActor < Hyrax::Actors::AbstractActor
      # @param [Hyrax::Actors::Environment] env
      # @return [Boolean] true if create was successful
      def create(env)
        remote_files = env.attributes.delete(:remote_files)
        next_actor.create(env) && attach_files(env, remote_files)
      end
      #…
    end
```

When presenting the `remote_url`, we have logic to convert these to A-tags (e.g. links); however that logic is expecting URLs and not paths.

As of <time datetime="2022-10-31">October 31, 2022</time>, when we look at <https://adl.b2.adventistdigitallibrary.org/concern/published_works/22220556_messiah_s_throne_and_millenial_glory?locale=en>, there are four related\_urls:

-   /downloads/91562cce-95c3-492e-9042-376694fe1095
-   /downloads/d20fdc35-c27d-4075-8bc5-c0b6fe68f74b
-   /downloads/eee4d959-d165-4828-9d6a-7060124f2344
-   /downloads/a3d3afed-054d-4405-9a3a-aca8778ca437

There are also 4 file sets:

-   **22220556.ARCHIVAL.pdf:** <https://adl.b2.adventistdigitallibrary.org/concern/parent/22220556_messiah_s_throne_and_millenial_glory/file_sets/d20fdc35-c27d-4075-8bc5-c0b6fe68f74b>
-   **22220556.X1.ARCHIVAL.pdf.TN.jpg:** <https://adl.b2.adventistdigitallibrary.org/concern/parent/22220556_messiah_s_throne_and_millenial_glory/file_sets/91562cce-95c3-492e-9042-376694fe1095>
-   **22220556.X1.RAW.txt:** <https://adl.b2.adventistdigitallibrary.org/concern/parent/22220556_messiah_s_throne_and_millenial_glory/file_sets/a3d3afed-054d-4405-9a3a-aca8778ca437>
-   **22220556.TN.jpg:** <https://adl.b2.adventistdigitallibrary.org/concern/parent/22220556_messiah_s_throne_and_millenial_glory/file_sets/eee4d959-d165-4828-9d6a-7060124f2344>

The last URL slugs match to the related URLs.

Reviewing [ADL and Hyku Maps.xlsx - Google Sheets](https://docs.google.com/spreadsheets/d/1GEsyaFNias1JmnAkRLZbMYsBIaV-1rxl/edit#gid=1720793301), we have a disconnect.  There is from the URL (e.g. MODS element `location/url`) to `related_url` in the Bulkrax mapping (see row 37 as of <time datetime="2022-10-31">2022-10-31</time>).  We have a `remote_url` (row 39 as of <time datetime="2022-10-31">2022-10-31</time>) in which we don’t map elements.

> 6.  Url is the current location for a remote resource. This is not the permanent URI.  A permanent URI should be included as an Identifier field in DC

At presenting our parser mappings in [config/initializers/bulkrax.rb](https://gitlab.com/notch8/adventist-dl/blob/4b808028faac007355c486f98076209475d75ccc/config/initializers/bulkrax.rb#L70-71) are confusing, in part because we replace the `remote_url` property with a custom SOLR Document method:

```ruby
    'remote_files' => { from: ['related_url'], split: ';', parsed: true },
    'remote_url' => { from: ['official_url', 'remote_url'], split: ';' },
```

To move forward we need to determine what the field name is for the files that we want to pull down and attach to the work.  This looks to be data contained in row 37 in the above spreadsheet.

**Comment by DeonFranklin** [comment]
Collection and Subcollection were successfully created.

![image](https://user-images.githubusercontent.com/95306716/204880611-3df7a78f-40a6-400c-8f97-fb4e286b7bab.png)


![image](https://user-images.githubusercontent.com/95306716/204880498-7529a0fd-bd0e-48cf-865a-9d3ea70b59f9.png)

**Comment by DeonFranklin** [comment]
The related url displays correctly on the edit and the show page.

![Image](https://user-images.githubusercontent.com/95306716/205547276-5f4dbebc-a83b-4cd7-ba23-e269638e4aea.png)



![Image](https://user-images.githubusercontent.com/95306716/205547350-cec397c1-c7a9-42f0-b80d-c57ef30d13c2.png)

**Comment by KatharineV** [comment]
Works brought into our digital library (on production) via OAI are still showing AWS S3 links in the metadata under "related URL." Ideally, we wouldn't see links in this field, at least not on the user side. The files are attached below the metdata and don't need to be repeated in the metadata as links to AWS. See this example which was uploaded via OAI on 29 December 2022: https://adl.b2.adventistdigitallibrary.org/concern/generic_works/22253560_wellsville_church_record_1877_to_1915?locale=en

**Comment by jeremyf** [comment]
OAI uses a different logic path than CSV.  At present, the OAI work tracks to https://github.com/scientist-softserv/adventist-dl/issues/201.

(One of my long-standing goals is to normalize those logic paths but there are nuances between XML, OAI, RDF, CSV, et al that need further analysis and road testing).

**Comment by KatharineV** [comment]
The AWS link is still showing in the "related URL" field of metadata on an OAI imported work (such as[ this Published Work](https://adl.s2.adventistdigitallibrary.org/concern/published_works/20121631_a_sketch_of_the_christian_experience_and_views_of_ellen_g_white?locale=en) imported on 2023-01-30). This is an example of a work on the digital library where we do not expect the Related URL field to show AWS links, because the files are supposed to attach to the work. 
However...
Question--In the example link given there, the files are not attached to the work as expected. Could this behavior be related to the overall ticket issue? The TXT file is present, but the PDF-A isn't. See screenshot for what I'm seeing today (2023-01-31), about 24 hours after importing the work: 


![Image](https://user-images.githubusercontent.com/118196520/215830057-2a143efc-b1c9-4ebc-b650-5e690ef7d1ca.png)

**Comment by jeremyf** [comment]
@KatharineV to clarify, I did not plan to remediate any of the data.  Instead I amended the importers with the intent of having clean future imports.  My question is then, does the above reflect a new importer that is not loading things correctly?

**Comment by KatharineV** [comment]
Closing because this seems complete.
