### ISSUE TITLE
Run RemoveAccountRelationshipsJob.perform_later on production to remove relationships

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#88]
In the Rails console:

```ruby
Account.all.each { |a| RemoveAccountRelationshipsJob.perform_later(a) }
```

**Comment by DiemBTran** [comment]
Linked items:

Blocks:

- Reimport data on production

Is blocked by:

- Run RemoveAccountRelationshipsJob on staging to remove relationships

**Comment by jillpe** [comment]
Closed in sprint meeting 11/14 - already completed
