### ISSUE TITLE
🦄 Spike: Universal Viewer is searchable

### ISSUE THREAD

**Issue by DiemBTran** [scientist-softserv/adventist-dl#96]
# Summary

Adventist would like their Universal Viewer to be searchable.

```gherkin
Given I have a PDF record
   And that PDF record has extracted images (and text) for each page of the PDF
   And I am looking at the universal viewer for that PDF record
When I search for a text term that exists in the PDF
Then the universal viewer should highlight the text that I searched for
```

```gherkin
Given I have a PDF record
   And that PDF record has extracted images (and text) for each page of the PDF
   And I'm on the `/catalog`
When I search for a text term that exists in the PDF
Then the `/catalog` search results will include a "hit" for the given PDF record
```

# Priority

This is of lower priority than:

- #402 

It is for their ADL tenant.

This duplicates:

- #73 

# Acceptance Criteria

- [x] The UV will highlight the text that is a hit for the search within UV
- [ ] Check to see if this is working, if not, create follow up tickets

# Examples

Looking to https://curiosity.lib.harvard.edu for implementation details

**Comment by DiemBTran** [comment]
Jeremy - Oct 2022

---

From 2022-10-10 Meeting:

> They brought in a bunch of text files with full text; there’s txt files.  Those were not indexed into the current system.  Hyku has FTS on a field and handles a PDF with embedded PDFs.
> 
> There exists txt files already attached; we want to index those for full-text search using the Blacklight FTS functions of Hyku.  <https://gitlab.com/notch8/adventist-dl/-/issues/147>
> 
> PDF NNP/PALS has an aspect of the OCR work that will be copy/pasted into adventist.  The second goal is I’m in the Universal Viewer and want to search within that work.
> 
> -   There’s a tie-through of the generic search to send to the viewer.  This should be part of NNP.
> -   We pushed them to use Tesseract but when scanned via NewspaperWorks we did not have good results.  The Abbyy results are far better.
> 
> Does Abbyy create derivatives?  Do they have a license agreement with Abbyy to use within the system?
>

**Comment by DiemBTran** [comment]
Jeremy - Oct 2022

---

Additional questions:

What we need is both the full text as well as the coordinates file (or equivalent) for each image.  We assume there’s a relationship between the coordinates file and the image; in otherwords if we have to generate/derive the images separate from the coordinates files there will invariably be drift.

Will *all* files have Abbyy files?  When providing an Abbyy file what other files are available?

What sort of audits do we need regarding appropriate data?  What is a typical works expected set of files?

**Comment by kirkkwang** [comment]
Example from Harvard for snippet
<img width="1123" alt="image" src="https://github.com/scientist-softserv/adventist-dl/assets/19597776/45b73e92-f3d3-4c78-9f6d-13e9a64fb7f2">

**Comment by jeremyf** [comment]
This is prioritized after the SDAPI import  and June 2023 deadline.
